const fs = require('fs'), p = require('path');
const BASE = p.join(__dirname, '..', 'src', 'data', 'exercises');
function mc(id, t, q, ops, r, exp) { return { id, tema: t, tipo: 'multiple_choice', nivel: 'v1', pregunta: q, opciones: ops, respuestaCorrecta: r, explicacion: exp }; }
function tf(id, t, q, r, exp) { return { id, tema: t, tipo: 'true_false', nivel: 'v1', pregunta: q, opciones: ['Verdadero', 'Falso'], respuestaCorrecta: r, explicacion: exp }; }
function sv(g, m, b, n, mes, ts, ejs) {
    const d = p.join(BASE, g, m); fs.mkdirSync(d, { recursive: true });
    fs.writeFileSync(p.join(d, 'bloque-' + b + '.json'), JSON.stringify({ grado: g, materia: m, bloque: b, nombre: n, meses: mes, temas: ts, totalEjercicios: ejs.length, ejercicios: { v1: ejs, v2: [], preview: ejs.slice(0, 2) } }, null, 2));
    console.log('  ✅ ' + g + '/' + m + '/bloque-' + b + ' (' + ejs.length + ' ejs)');
}
const G = 'secundaria-1';

// ═══ ARTES ═══
console.log('\n🎨 ARTES — ' + G);
sv(G, 'artes', 1, 'Elementos del arte visual', 'Ago-Sep', ['Color', 'Forma', 'Línea', 'Textura'], [
    mc('s1art-b1-01', 'Color', '¿Cuáles son los 3 colores primarios?', ['Rojo, azul y amarillo', 'Verde, naranja y morado', 'Blanco, negro y gris', 'Rosa, café y beige'], 'Rojo, azul y amarillo', 'Los colores primarios no se obtienen mezclando otros y son la base del círculo cromático.'),
    mc('s1art-b1-02', 'Color', '¿Qué color se obtiene al mezclar azul y amarillo?', ['Verde', 'Naranja', 'Morado', 'Café'], 'Verde', 'Azul + amarillo = verde. Es un color secundario.'),
    tf('s1art-b1-03', 'Forma', 'Un triángulo tiene 4 lados', 'Falso', 'El triángulo tiene 3 lados y 3 ángulos. El cuadrado tiene 4 lados.'),
    mc('s1art-b1-04', 'Línea', '¿Qué tipo de línea no tiene curvas?', ['Recta', 'Ondulada', 'Espiral', 'Curva'], 'Recta', 'La línea recta va de punto a punto sin cambiar de dirección.'),
    mc('s1art-b1-05', 'Textura', '¿Qué es la textura en el arte?', ['La sensación de superficie de un material', 'El color de la obra', 'El tamaño del dibujo', 'El nombre del artista'], 'La sensación de superficie de un material', 'La textura puede ser rugosa, lisa, áspera, suave, etc.'),
    tf('s1art-b1-06', 'Arte', 'El dibujo y la pintura son formas de arte visual', 'Verdadero', 'El arte visual incluye dibujo, pintura, escultura, fotografía y más.'),
    mc('s1art-b1-07', 'Color', '¿Qué son los colores cálidos?', ['Rojos, naranjas y amarillos', 'Azules, verdes y morados', 'Blancos y negros', 'Grises y cafés'], 'Rojos, naranjas y amarillos', 'Los colores cálidos evocan calor, energía y pasión.'),
    mc('s1art-b1-08', 'Composición', '¿Qué es la composición en arte?', ['La organización de elementos visuales en una obra', 'Solo el color', 'Solo el tamaño', 'El precio de la obra'], 'La organización de elementos visuales en una obra', 'La composición decide dónde colocar cada elemento para crear armonía visual.'),
    tf('s1art-b1-09', 'Color', 'Los colores fríos incluyen azul, verde y violeta', 'Verdadero', 'Los colores fríos transmiten calma, frescura y tranquilidad.'),
    mc('s1art-b1-10', 'Arte', '¿Qué herramienta usa principalmente un pintor?', ['Pincel y lienzo', 'Cincel y mármol', 'Cámara fotográfica', 'Guitarra'], 'Pincel y lienzo', 'El pincel aplica pintura sobre el lienzo (tela preparada para pintar).'),
]);
sv(G, 'artes', 2, 'Arte prehispánico y muralismo mexicano', 'Oct-Nov', ['Arte prehispánico', 'Muralismo'], [
    mc('s1art-b2-01', 'Muralismo', '¿Qué es el muralismo mexicano?', ['Movimiento artístico de pintura en muros públicos', 'Escultura en madera', 'Fotografía artística', 'Arte digital'], 'Movimiento artístico de pintura en muros públicos', 'El muralismo plasmó la historia y luchas de México en paredes de edificios públicos.'),
    mc('s1art-b2-02', 'Muralismo', '¿Quiénes son los "tres grandes" del muralismo?', ['Rivera, Orozco y Siqueiros', 'Kahlo, Tamayo y Rivera', 'Picasso, Dalí y Miró', 'Van Gogh, Monet y Renoir'], 'Rivera, Orozco y Siqueiros', 'Diego Rivera, José Clemente Orozco y David Alfaro Siqueiros son los tres grandes muralistas.'),
    tf('s1art-b2-03', 'Prehispánico', 'Las pirámides mayas y aztecas son obras arquitectónicas', 'Verdadero', 'La arquitectura prehispánica combina arte, ciencia y espiritualidad.'),
    mc('s1art-b2-04', 'Prehispánico', '¿Cuál es un ejemplo de arte prehispánico?', ['La Piedra del Sol (Calendario Azteca)', 'La Mona Lisa', 'El David de Miguel Ángel', 'La Torre Eiffel'], 'La Piedra del Sol (Calendario Azteca)', 'La Piedra del Sol es una obra maestra de arte y ciencia azteca.'),
    mc('s1art-b2-05', 'Artistas', 'Frida Kahlo era famosa por:', ['Sus autorretratos que expresaban dolor e identidad', 'Sus murales gigantes', 'Sus esculturas de bronce', 'Sus fotografías de paisajes'], 'Sus autorretratos que expresaban dolor e identidad', 'Frida pintó su realidad personal con simbolismo mexicano profundo.'),
    tf('s1art-b2-06', 'Muralismo', 'El muralismo surgió después de la Revolución Mexicana', 'Verdadero', 'El muralismo nació en los años 1920s como herramienta educativa post-revolucionaria.'),
    mc('s1art-b2-07', 'Prehispánico', '¿Qué material usaban los mayas para sus esculturas?', ['Piedra caliza', 'Plástico', 'Metal moderno', 'Vidrio'], 'Piedra caliza', 'Los mayas trabajaban piedra caliza para estelas, dinteles y fachadas monumentales.'),
    mc('s1art-b2-08', 'Artistas', 'Rufino Tamayo se distinguía de los muralistas por:', ['Usar colores vibrantes y temas universales, no solo políticos', 'No pintar nunca', 'Solo hacer esculturas', 'Copiar a Rivera'], 'Usar colores vibrantes y temas universales, no solo políticos', 'Tamayo fusionó lo mexicano con tendencias de vanguardia internacional.'),
    tf('s1art-b2-09', 'Muralismo', 'Los murales de la UNAM son Patrimonio de la Humanidad', 'Verdadero', 'La UNAM fue declarada Patrimonio por la UNESCO, incluyendo sus murales.'),
    mc('s1art-b2-10', 'Arte', '¿Qué es un autorretrato?', ['Un retrato que el artista hace de sí mismo', 'Un paisaje', 'Una naturaleza muerta', 'Un retrato de otra persona'], 'Un retrato que el artista hace de sí mismo', 'Auto = uno mismo. Auto + retrato = retrato de sí mismo.'),
]);
sv(G, 'artes', 3, 'Música: elementos fundamentales', 'Dic-Ene', ['Ritmo', 'Melodía', 'Instrumentos'], [
    mc('s1art-b3-01', 'Melodía', '¿Qué es la melodía?', ['Sucesión de notas musicales que forman una canción', 'El volumen', 'Solo el ritmo', 'Los instrumentos'], 'Sucesión de notas musicales que forman una canción', 'La melodía es la parte que reconocemos y podemos tararear de una canción.'),
    mc('s1art-b3-02', 'Instrumentos', '¿A qué familia pertenece la guitarra?', ['Cuerdas', 'Vientos', 'Percusión', 'Electrónica'], 'Cuerdas', 'La guitarra produce sonido vibrando sus 6 cuerdas.'),
    tf('s1art-b3-03', 'Percusión', 'Un tambor es un instrumento de percusión', 'Verdadero', 'Los instrumentos de percusión producen sonido al ser golpeados: tambor, maracas, xilófono.'),
    mc('s1art-b3-04', 'Escala', '¿Cuántas notas tiene la escala musical básica?', ['7: Do, Re, Mi, Fa, Sol, La, Si', '5', '10', '12'], '7: Do, Re, Mi, Fa, Sol, La, Si', 'La escala diatónica tiene 7 notas naturales.'),
    mc('s1art-b3-05', 'Instrumentos', 'La flauta es un instrumento de:', ['Viento', 'Cuerda', 'Percusión', 'Teclado'], 'Viento', 'Los instrumentos de viento producen sonido por el aire que pasa a través de ellos.'),
    tf('s1art-b3-06', 'Instrumentos', 'El violín se toca con un arco', 'Verdadero', 'El arco frota las cuerdas del violín para producir sonido.'),
    mc('s1art-b3-07', 'Ritmo', '¿Qué es el tempo en música?', ['La velocidad a la que se interpreta la música', 'El volumen', 'La melodía principal', 'El nombre de la canción'], 'La velocidad a la que se interpreta la música', 'Allegro = rápido, Adagio = lento, Andante = moderado.'),
    mc('s1art-b3-08', 'Instrumentos', '¿Qué instrumento de percusión es tradicional de Chiapas?', ['La marimba', 'El violín', 'La guitarra', 'La trompeta'], 'La marimba', 'La marimba es un instrumento de percusión emblemático de Chiapas y Oaxaca.'),
    tf('s1art-b3-09', 'Ritmo', 'El compás organiza la música en grupos regulares de tiempos', 'Verdadero', 'El compás más común es 4/4: cuatro tiempos por compás.'),
    mc('s1art-b3-10', 'Música', '¿Qué es la armonía en música?', ['La combinación de notas que suenan al mismo tiempo', 'Solo tocar fuerte', 'Solo la letra', 'El nombre del grupo'], 'La combinación de notas que suenan al mismo tiempo', 'La armonía son acordes (varias notas simultáneas) que acompañan la melodía.'),
]);
sv(G, 'artes', 4, 'Teatro y expresión escénica', 'Feb-Mar', ['Elementos del teatro', 'Géneros dramáticos'], [
    mc('s1art-b4-01', 'Teatro', '¿Cuáles son los elementos básicos del teatro?', ['Actor, texto, espacio escénico y público', 'Solo el actor', 'Solo el texto', 'Solo el escenario'], 'Actor, texto, espacio escénico y público', 'El teatro necesita alguien que actúe, algo que decir, un lugar y alguien que observe.'),
    mc('s1art-b4-02', 'Géneros', '¿Cuáles son los dos géneros dramáticos principales?', ['Tragedia y comedia', 'Romance y terror', 'Acción y drama', 'Musical y ópera'], 'Tragedia y comedia', 'La tragedia termina en desgracia; la comedia busca la risa y tiene final feliz.'),
    tf('s1art-b4-03', 'Teatro', 'El escenario es donde actúan los actores', 'Verdadero', 'El escenario es el espacio designado para la representación teatral.'),
    mc('s1art-b4-04', 'Teatro', '¿Qué es el guión teatral?', ['El texto con diálogos y acotaciones de la obra', 'El vestuario', 'La música de fondo', 'Las luces del escenario'], 'El texto con diálogos y acotaciones de la obra', 'El guión contiene todo lo que dicen los personajes y las instrucciones escénicas.'),
    mc('s1art-b4-05', 'Teatro', '¿Qué es la improvisación teatral?', ['Crear escenas sin guión previo, en el momento', 'Memorizar todo perfectamente', 'Leer el guión en voz alta', 'No actuar'], 'Crear escenas sin guión previo, en el momento', 'La improvisación desarrolla creatividad, espontaneidad y trabajo en equipo.'),
    tf('s1art-b4-06', 'Teatro', 'La pantomima usa palabras para comunicar', 'Falso', 'La pantomima se hace en silencio, comunicando solo con gestos y movimientos corporales.'),
    mc('s1art-b4-07', 'Teatro', '¿Cuál es el origen del teatro occidental?', ['La Antigua Grecia', 'El Antiguo Egipto', 'Roma', 'China'], 'La Antigua Grecia', 'El teatro occidental nació en Atenas con dramaturgos como Sófocles y Eurípides.'),
    mc('s1art-b4-08', 'Teatro', '¿Qué función tiene el director de teatro?', ['Coordinar todos los elementos de la puesta en escena', 'Solo memorizar textos', 'Solo vender boletos', 'Solo maquillarse'], 'Coordinar todos los elementos de la puesta en escena', 'El director dirige actores, escenografía, luces, vestuario y música.'),
    tf('s1art-b4-09', 'Teatro', 'El vestuario ayuda a definir la época y personalidad del personaje', 'Verdadero', 'El vestuario comunica visualmente quién es el personaje y en qué época vive.'),
    mc('s1art-b4-10', 'Teatro', '¿Qué habilidad personal desarrolla más el teatro?', ['Expresión oral, confianza y empatía', 'Solo memorización', 'Solo fuerza física', 'Solo matemáticas'], 'Expresión oral, confianza y empatía', 'El teatro enseña a comunicarse, a ponerse en el lugar de otros y a perder el miedo escénico.'),
]);
sv(G, 'artes', 5, 'Arte contemporáneo y digital', 'Abr-Jun', ['Arte moderno', 'Arte digital', 'Fotografía'], [
    mc('s1art-b5-01', 'Moderno', '¿Qué es el arte abstracto?', ['Arte que no representa objetos reales reconocibles', 'Pintura hiperrealista', 'Fotografía de naturaleza', 'Escultura clásica'], 'Arte que no representa objetos reales reconocibles', 'El arte abstracto expresa emociones o ideas mediante formas, colores y líneas libres.'),
    mc('s1art-b5-02', 'Digital', '¿Cuál es una forma de arte digital?', ['Diseño gráfico, animación, arte generado por IA', 'Solo pintura rupestre', 'Solo escultura en piedra', 'Solo óleo sobre lienzo'], 'Diseño gráfico, animación, arte generado por IA', 'El arte digital usa herramientas tecnológicas para crear imágenes y experiencias.'),
    tf('s1art-b5-03', 'Fotografía', 'La fotografía artística es reconocida como forma de arte', 'Verdadero', 'La fotografía captura momentos, emociones y perspectivas de forma artística.'),
    mc('s1art-b5-04', 'Moderno', '¿Quién creó el cubismo?', ['Pablo Picasso y Georges Braque', 'Leonardo da Vinci', 'Miguel Ángel', 'Claude Monet'], 'Pablo Picasso y Georges Braque', 'El cubismo muestra objetos desde múltiples ángulos simultáneamente.'),
    mc('s1art-b5-05', 'Digital', 'El cine es considerado:', ['El séptimo arte', 'Solo entretenimiento comercial', 'Arte menor', 'No es arte'], 'El séptimo arte', 'El cine combina narrativa, imagen, sonido, actuación y música en una obra audiovisual.'),
    tf('s1art-b5-06', 'Arte urbano', 'El arte urbano (graffiti, murales callejeros) puede ser arte legítimo', 'Verdadero', 'Artistas como Banksy han elevado el arte urbano a categoría de arte contemporáneo reconocido.'),
    mc('s1art-b5-07', 'Moderno', '¿Qué es una instalación artística?', ['Obra tridimensional que transforma un espacio y puede recorrerse', 'Un cuadro pequeño', 'Una foto', 'Un dibujo a lápiz'], 'Obra tridimensional que transforma un espacio y puede recorrerse', 'Las instalaciones son experiencias inmersivas que el espectador habita.'),
    mc('s1art-b5-08', 'Digital', '¿Qué es la animación?', ['Crear la ilusión de movimiento con imágenes', 'Pintar cuadros', 'Esculpir piedra', 'Tocar música'], 'Crear la ilusión de movimiento con imágenes', 'La animación da vida a personajes e historias mediante secuencias de imágenes.'),
    tf('s1art-b5-09', 'Arte', 'El arte sirve para expresar ideas, emociones y cultura', 'Verdadero', 'El arte es un lenguaje universal que comunica lo que las palabras no siempre pueden.'),
    mc('s1art-b5-10', 'Contemporáneo', '¿Qué es el performance artístico?', ['Una obra donde el artista usa su cuerpo como medio de expresión en vivo', 'Solo un concierto', 'Solo una película', 'Solo una pintura'], 'Una obra donde el artista usa su cuerpo como medio de expresión en vivo', 'El performance es arte efímero que ocurre en tiempo real ante el público.'),
]);

// ═══ ED. FÍSICA ═══
console.log('\n🏃 ED. FÍSICA — ' + G);
sv(G, 'educacion_fisica', 1, 'Actividad física y salud', 'Ago-Sep', ['Beneficios del ejercicio', 'Capacidades físicas'], [
    mc('s1ef-b1-01', 'Salud', '¿Cuántos minutos diarios de actividad física recomienda la OMS para adolescentes?', ['60 minutos', '10 minutos', '120 minutos', '5 minutos'], '60 minutos', 'La OMS recomienda mínimo 60 minutos diarios de actividad moderada-vigorosa para jóvenes.'),
    mc('s1ef-b1-02', 'Capacidades', 'Las capacidades físicas básicas son:', ['Fuerza, velocidad, resistencia y flexibilidad', 'Solo correr', 'Solo nadar', 'Solo dormir'], 'Fuerza, velocidad, resistencia y flexibilidad', 'Estas 4 capacidades son el fundamento de todo rendimiento deportivo.'),
    tf('s1ef-b1-03', 'Salud', 'El ejercicio regular reduce el riesgo de enfermedades cardiovasculares', 'Verdadero', 'El ejercicio fortalece el corazón, mejora la circulación y reduce la presión arterial.'),
    mc('s1ef-b1-04', 'Sedentarismo', '¿Qué es el sedentarismo?', ['Estilo de vida con poca actividad física', 'Hacer mucho deporte', 'Comer saludable', 'Dormir 8 horas'], 'Estilo de vida con poca actividad física', 'El sedentarismo es factor de riesgo para obesidad, diabetes y enfermedades del corazón.'),
    mc('s1ef-b1-05', 'Ejercicio', '¿Qué incluye un calentamiento correcto?', ['Movilidad articular y elevación gradual de la frecuencia cardíaca', 'Correr a máxima velocidad', 'Estiramientos estáticos fuertes', 'Sentarse 10 minutos'], 'Movilidad articular y elevación gradual de la frecuencia cardíaca', 'El calentamiento activa articulaciones, músculos y el sistema cardiovascular progresivamente.'),
    tf('s1ef-b1-06', 'Salud', 'El ejercicio físico mejora la concentración y el rendimiento académico', 'Verdadero', 'La actividad física aumenta el flujo sanguíneo al cerebro, mejorando la atención y memoria.'),
    mc('s1ef-b1-07', 'Capacidades', '¿Qué capacidad permite correr 100 metros lo más rápido posible?', ['Velocidad', 'Resistencia', 'Flexibilidad', 'Equilibrio'], 'Velocidad', 'La velocidad es la capacidad de desplazarse a máxima rapidez en distancias cortas.'),
    mc('s1ef-b1-08', 'Ejercicio', '¿Para qué sirve la vuelta a la calma?', ['Reducir gradualmente la frecuencia cardíaca y prevenir mareos', 'Cansar más al cuerpo', 'Nada importante', 'Aumentar la velocidad'], 'Reducir gradualmente la frecuencia cardíaca y prevenir mareos', 'El enfriamiento evita que la sangre se acumule en las extremidades causando mareos.'),
    tf('s1ef-b1-09', 'Hidratación', 'Hidratarse antes, durante y después del ejercicio es fundamental', 'Verdadero', 'El agua regula la temperatura corporal y mantiene las funciones vitales durante el ejercicio.'),
    mc('s1ef-b1-10', 'Capacidades', 'La resistencia aeróbica nos permite:', ['Mantener actividad física prolongada', 'Levantar objetos muy pesados', 'Estirarnos mucho', 'Reaccionar rápidamente'], 'Mantener actividad física prolongada', 'La resistencia aeróbica usa oxígeno para producir energía durante esfuerzos prolongados.'),
]);
sv(G, 'educacion_fisica', 2, 'Deportes y reglamentos', 'Oct-Nov', ['Futbol', 'Basquetbol', 'Fair play'], [
    mc('s1ef-b2-01', 'Futbol', '¿Cuántos jugadores tiene cada equipo de futbol en cancha?', ['11', '9', '7', '13'], '11', 'Cada equipo tiene 11 jugadores incluyendo al portero.'),
    mc('s1ef-b2-02', 'Basquetbol', '¿Cuántos puntos vale un triple en basquetbol?', ['3', '2', '1', '4'], '3', 'Los tiros desde fuera de la línea de tres puntos valen 3.'),
    tf('s1ef-b2-03', 'Fair play', 'El juego limpio (fair play) significa respetar reglas y rivales', 'Verdadero', 'El fair play es la base ética de todo deporte: respeto, honestidad y deportividad.'),
    mc('s1ef-b2-04', 'Voleibol', '¿Cuántos toques máximo puede dar un equipo en voleibol?', ['3 toques', '5 toques', '1 toque', 'Ilimitados'], '3 toques', 'Recepción, armado y remate: 3 toques antes de devolver el balón.'),
    mc('s1ef-b2-05', 'Reglas', 'La tarjeta roja en futbol significa:', ['Expulsión del jugador', 'Advertencia', 'Tiro libre', 'Saque de esquina'], 'Expulsión del jugador', 'La roja expulsa al jugador. La amarilla es advertencia.'),
    tf('s1ef-b2-06', 'Fair play', 'Insultar al árbitro es parte normal del deporte', 'Falso', 'Es antideportivo y puede resultar en sanciones. El respeto al árbitro es obligatorio.'),
    mc('s1ef-b2-07', 'Historia', '¿Quién inventó el basquetbol?', ['James Naismith en 1891', 'Pelé en 1960', 'Pierre de Coubertin en 1896', 'Michael Jordan en 1984'], 'James Naismith en 1891', 'Naismith creó el basquetbol en Springfield, Massachusetts, como deporte de invierno.'),
    mc('s1ef-b2-08', 'Atletismo', 'El atletismo incluye:', ['Carreras, saltos y lanzamientos', 'Solo natación', 'Solo gimnasia', 'Solo futbol'], 'Carreras, saltos y lanzamientos', 'El atletismo es el deporte más antiguo y base de los Juegos Olímpicos.'),
    tf('s1ef-b2-09', 'Fair play', 'Ayudar a un rival lesionado es buena deportividad', 'Verdadero', 'La solidaridad con el rival lesionado demuestra los valores más altos del deporte.'),
    mc('s1ef-b2-10', 'Deportes', '¿Qué deporte de raqueta se juega con un "gallito" (shuttlecock)?', ['Bádminton', 'Tenis', 'Ping-pong', 'Squash'], 'Bádminton', 'El bádminton usa una plumilla ligera en lugar de pelota.'),
]);
sv(G, 'educacion_fisica', 3, 'Nutrición deportiva', 'Dic-Ene', ['Macronutrientes', 'Dieta del adolescente deportista'], [
    mc('s1ef-b3-01', 'Nutrición', '¿Cuál es la principal fuente de energía para el ejercicio intenso?', ['Carbohidratos', 'Solo proteínas', 'Solo grasas', 'Solo vitaminas'], 'Carbohidratos', 'Los carbohidratos proporcionan glucosa, el combustible preferido de los músculos activos.'),
    mc('s1ef-b3-02', 'Proteínas', '¿Qué macronutriente repara y construye tejido muscular?', ['Proteína', 'Carbohidratos', 'Grasas', 'Agua'], 'Proteína', 'Las proteínas son los bloques constructores del músculo.'),
    tf('s1ef-b3-03', 'Nutrición', 'Las bebidas energéticas son recomendables para todos los adolescentes', 'Falso', 'Contienen exceso de cafeína y azúcar. No son recomendables para menores de edad.'),
    mc('s1ef-b3-04', 'Hidratación', '¿Cuándo debemos hidratarnos durante el ejercicio?', ['Antes, durante y después', 'Solo al terminar', 'Solo si tenemos mucha sed', 'Nunca durante el ejercicio'], 'Antes, durante y después', 'La hidratación constante mantiene el rendimiento y previene el agotamiento.'),
    mc('s1ef-b3-05', 'Nutrición', 'Fuentes de proteína saludable incluyen:', ['Pollo, huevo, frijoles, lentejas', 'Solo suplementos', 'Solo bebidas proteicas', 'Solo carne roja'], 'Pollo, huevo, frijoles, lentejas', 'Carnes magras, huevo y leguminosas son excelentes fuentes proteicas naturales.'),
    tf('s1ef-b3-06', 'Grasas', 'Las grasas saludables (aguacate, nueces, aceite de oliva) son necesarias', 'Verdadero', 'Las grasas insaturadas son esenciales para el cerebro, hormonas y absorción de vitaminas.'),
    mc('s1ef-b3-07', 'IMC', '¿Qué es el IMC?', ['Índice de Masa Corporal: peso(kg)/estatura(m)²', 'Solo el peso', 'Solo la estatura', 'El porcentaje de grasa'], 'Índice de Masa Corporal: peso(kg)/estatura(m)²', 'El IMC es una referencia básica para evaluar si estamos en un rango de peso saludable.'),
    mc('s1ef-b3-08', 'Nutrición', '¿Cuándo es mejor comer antes de hacer ejercicio?', ['1 a 2 horas antes', 'Justo antes de empezar', '5 horas antes', 'No comer'], '1 a 2 horas antes', 'Comer 1-2 horas antes permite digestión adecuada y energía disponible.'),
    tf('s1ef-b3-09', 'Nutrición', 'Los alimentos ultraprocesados reducen el rendimiento deportivo', 'Verdadero', 'Exceso de azúcar, sodio y grasas malas afectan negativamente la energía y recuperación.'),
    mc('s1ef-b3-10', 'Vitaminas', 'La vitamina D, importante para huesos, se obtiene principalmente de:', ['La exposición solar y alimentos como pescado', 'Solo suplementos', 'Solo dulces', 'Solo refrescos'], 'La exposición solar y alimentos como pescado', 'La vitamina D se sintetiza con sol y se encuentra en pescados grasos y huevo.'),
]);
sv(G, 'educacion_fisica', 4, 'Prevención de lesiones', 'Feb-Mar', ['RICE', 'Primeros auxilios deportivos'], [
    mc('s1ef-b4-01', 'Lesiones', '¿Qué es un esguince?', ['Estiramiento o ruptura parcial de ligamentos', 'Una fractura', 'Un corte', 'Solo un moretón'], 'Estiramiento o ruptura parcial de ligamentos', 'El esguince ocurre cuando una articulación se tuerce más allá de su rango normal.'),
    mc('s1ef-b4-02', 'RICE', '¿Qué significa R.I.C.E.?', ['Rest, Ice, Compression, Elevation', 'Run, Imagine, Create, Enjoy', 'Rapid Intense Continuous Exercise', 'Nada'], 'Rest, Ice, Compression, Elevation', 'RICE (Reposo, Hielo, Compresión, Elevación) es el tratamiento básico para lesiones leves.'),
    tf('s1ef-b4-03', 'Prevención', 'Un buen calentamiento previene la mayoría de lesiones deportivas', 'Verdadero', 'Músculos y articulaciones calientes son más elásticos y resistentes a lesiones.'),
    mc('s1ef-b4-04', 'Primeros auxilios', 'Ante una persona inconsciente, ¿qué hacemos primero?', ['Verificar si respira y llamar al 911', 'Moverla rápidamente', 'Darle agua', 'Abandonarla'], 'Verificar si respira y llamar al 911', 'La prioridad: vía aérea, respiración y llamar a servicios de emergencia.'),
    mc('s1ef-b4-05', 'Hielo', '¿Cómo actúa el hielo en una lesión?', ['Reduce inflamación y dolor al disminuir el flujo sanguíneo local', 'Cura el hueso', 'Limpia heridas', 'Aumenta la inflamación'], 'Reduce inflamación y dolor al disminuir el flujo sanguíneo local', 'El frío contrae los vasos sanguíneos, reduciendo la hinchazón y el dolor.'),
    tf('s1ef-b4-06', 'Equipo', 'El equipo de protección adecuado previene lesiones graves', 'Verdadero', 'Casco, rodilleras, espinilleras y calzado adecuado son fundamentales según el deporte.'),
    mc('s1ef-b4-07', 'RCP', '¿Cuántas compresiones por minuto se hacen en RCP?', ['100 a 120', '10', '50', '200'], '100 a 120', 'El ritmo de 100-120 compresiones/minuto mantiene la circulación sanguínea básica.'),
    mc('s1ef-b4-08', 'Lesiones', '¿Qué debemos hacer si sentimos dolor agudo durante el ejercicio?', ['Parar inmediatamente y avisar al profesor', 'Seguir a pesar del dolor', 'Ignorarlo', 'Correr más rápido'], 'Parar inmediatamente y avisar al profesor', 'El dolor agudo es señal de alarma. Continuar puede empeorar la lesión.'),
    tf('s1ef-b4-09', 'Columna', 'No debemos mover a alguien con posible lesión en la columna', 'Verdadero', 'Mover a alguien con lesión espinal puede causar parálisis. Esperar a los paramédicos.'),
    mc('s1ef-b4-10', 'Prevención', '¿Qué previene las lesiones por sobreuso?', ['Respetar días de descanso y variar ejercicios', 'Entrenar todos los días sin parar', 'Solo comer bien', 'Ignorar la fatiga'], 'Respetar días de descanso y variar ejercicios', 'El descanso permite que los tejidos se recuperen y fortalezcan.'),
]);
sv(G, 'educacion_fisica', 5, 'Deporte, valores y sociedad', 'Abr-Jun', ['Olimpismo', 'Inclusión deportiva', 'Vida activa'], [
    mc('s1ef-b5-01', 'Valores', '¿Qué valor del deporte nos enseña a manejar la derrota?', ['Resiliencia y autocontrol', 'Solo la fuerza', 'Solo la velocidad', 'El tamaño físico'], 'Resiliencia y autocontrol', 'El deporte enseña a levantarse de las derrotas y controlar las emociones.'),
    mc('s1ef-b5-02', 'Olimpismo', '¿Cada cuántos años son los Juegos Olímpicos de verano?', ['Cada 4 años', 'Cada año', 'Cada 2 años', 'Cada 10 años'], 'Cada 4 años', 'Los JJOO de verano se celebran cada 4 años desde 1896.'),
    tf('s1ef-b5-03', 'Inclusión', 'El deporte puede ser herramienta de inclusión social', 'Verdadero', 'El deporte une personas de todas las culturas, capacidades y orígenes.'),
    mc('s1ef-b5-04', 'Salud', '¿Cuántos días por semana recomienda la OMS de ejercicio moderado para adolescentes?', ['Todos los días (al menos 60 min diarios)', 'Solo 1 día', 'Solo fines de semana', '2 días'], 'Todos los días (al menos 60 min diarios)', 'La OMS recomienda que los jóvenes sean activos todos los días.'),
    mc('s1ef-b5-05', 'Dopaje', '¿Qué es el dopaje?', ['Uso de sustancias prohibidas para mejorar el rendimiento', 'Entrenamiento intenso', 'Dieta especial', 'Cambiar de equipo'], 'Uso de sustancias prohibidas para mejorar el rendimiento', 'El dopaje es trampa, pone en riesgo la salud y destruye carreras deportivas.'),
    tf('s1ef-b5-06', 'Paralímpicos', 'Los atletas paralímpicos compiten con igual dedicación que los olímpicos', 'Verdadero', 'Los atletas paralímpicos demuestran que el deporte es para TODOS.'),
    mc('s1ef-b5-07', 'Inclusión', '¿Qué es el deporte adaptado?', ['Actividad deportiva modificada para personas con discapacidad', 'Solo deporte para niños', 'Ejercicio sin reglas', 'Deporte sin esfuerzo'], 'Actividad deportiva modificada para personas con discapacidad', 'El deporte adaptado modifica reglas y equipos para la participación de todos.'),
    mc('s1ef-b5-08', 'Vida sana', '¿Cuál es la clave de una vida saludable?', ['Equilibrio entre ejercicio, nutrición y descanso', 'Solo hacer dieta', 'Solo hacer ejercicio', 'Solo dormir'], 'Equilibrio entre ejercicio, nutrición y descanso', 'La salud integral requiere los tres pilares en equilibrio.'),
    tf('s1ef-b5-09', 'Deporte', 'Cualquier persona puede encontrar una actividad física adecuada para ella', 'Verdadero', 'Siempre existe una actividad que se adapte a las capacidades e intereses de cada persona.'),
    mc('s1ef-b5-10', 'Valores', 'El deporte nos enseña principalmente:', ['Disciplina, trabajo en equipo, perseverancia y respeto', 'Solo a ganar', 'Solo a competir', 'A ser agresivos'], 'Disciplina, trabajo en equipo, perseverancia y respeto', 'Estos valores deportivos son transferibles a todos los ámbitos de la vida.'),
]);

console.log('\n✅ SECUNDARIA 1° — Artes (50) + Ed. Física (50) = 100 ejercicios COMPLETOS');
