const fs = require('fs'), p = require('path');
const BASE = p.join(__dirname, '..', 'src', 'data', 'exercises');
function mc(id, t, q, ops, r, exp) { return { id, tema: t, tipo: 'multiple_choice', nivel: 'v1', pregunta: q, opciones: ops, respuestaCorrecta: r, explicacion: exp }; }
function tf(id, t, q, r, exp) { return { id, tema: t, tipo: 'true_false', nivel: 'v1', pregunta: q, opciones: ['Verdadero', 'Falso'], respuestaCorrecta: r, explicacion: exp }; }
function sv(g, m, b, n, mes, ts, ejs) {
    const d = p.join(BASE, g, m); fs.mkdirSync(d, { recursive: true });
    fs.writeFileSync(p.join(d, 'bloque-' + b + '.json'), JSON.stringify({ grado: g, materia: m, bloque: b, nombre: n, meses: mes, temas: ts, totalEjercicios: ejs.length, ejercicios: { v1: ejs, v2: [], preview: ejs.slice(0, 2) } }, null, 2));
    console.log('  ✅ ' + g + '/' + m + '/bloque-' + b + ' (' + ejs.length + ' ejs)');
}
const G = 'secundaria-2';

// ═══ ARTES ═══
console.log('\n🎨 ARTES — ' + G);
sv(G, 'artes', 1, 'Lenguajes artísticos', 'Ago-Sep', ['Artes visuales', 'Artes escénicas', 'Artes sonoras'], [
    mc('s2art-b1-01', 'Lenguajes', '¿Cuáles son los principales lenguajes artísticos?', ['Visual, musical, teatral y de danza', 'Solo pintura', 'Solo música', 'Solo cine'], 'Visual, musical, teatral y de danza', 'Las artes se expresan mediante imágenes, sonidos, movimiento y representación escénica.'),
    mc('s2art-b1-02', 'Visual', '¿Qué técnica usa pigmentos mezclados con aceite?', ['Pintura al óleo', 'Acuarela', 'Lápiz de color', 'Pastel seco'], 'Pintura al óleo', 'El óleo usa pigmentos con aceite de linaza, dando colores intensos y duraderos.'),
    tf('s2art-b1-03', 'Artes', 'La danza combina movimiento corporal con música', 'Verdadero', 'La danza es arte del movimiento rítmico del cuerpo, generalmente acompañado de música.'),
    mc('s2art-b1-04', 'Visual', '¿Qué es la perspectiva en dibujo?', ['Técnica para crear profundidad y distancia en una superficie plana', 'Solo colorear', 'Hacer líneas rectas', 'Copiar fotos'], 'Técnica para crear profundidad y distancia en una superficie plana', 'La perspectiva simula la tercera dimensión en una hoja o lienzo de dos dimensiones.'),
    mc('s2art-b1-05', 'Musical', '¿Qué es la polifonía en música?', ['Varias melodías sonando simultáneamente', 'Una sola nota', 'Solo ritmo sin melodía', 'Música sin instrumentos'], 'Varias melodías sonando simultáneamente', 'La polifonía es la combinación de varias voces o líneas melódicas independientes.'),
    tf('s2art-b1-06', 'Escénicas', 'El cine combina artes visuales, sonoras y escénicas', 'Verdadero', 'El cine integra imagen, sonido, actuación, iluminación y narrativa en una sola obra.'),
    mc('s2art-b1-07', 'Danza', '¿Cuál es la diferencia entre danza folclórica y contemporánea?', ['La folclórica preserva tradiciones; la contemporánea experimenta con nuevas formas', 'No hay diferencia', 'Solo el vestuario', 'Solo la música'], 'La folclórica preserva tradiciones; la contemporánea experimenta con nuevas formas', 'La danza folclórica mantiene raíces culturales; la contemporánea busca innovación expresiva.'),
    mc('s2art-b1-08', 'Visual', '¿Qué es un boceto?', ['Dibujo rápido y preliminar de una idea artística', 'La obra final', 'Una fotografía', 'Un marco para cuadros'], 'Dibujo rápido y preliminar de una idea artística', 'El boceto es el primer paso para planear una obra antes de la versión definitiva.'),
    tf('s2art-b1-09', 'Artes', 'El arte puede transmitir mensajes sociales y políticos', 'Verdadero', 'A lo largo de la historia, el arte ha sido vehículo de denuncia, protesta y cambio social.'),
    mc('s2art-b1-10', 'Musical', '¿Qué género musical es típicamente mexicano?', ['El son jarocho, el huapango y el mariachi', 'El jazz', 'El rock británico', 'La ópera italiana'], 'El son jarocho, el huapango y el mariachi', 'México tiene una rica variedad de géneros musicales regionales con identidad propia.'),
]);
sv(G, 'artes', 2, 'Arte y cultura en México', 'Oct-Nov', ['Patrimonio cultural', 'Arte popular mexicano'], [
    mc('s2art-b2-01', 'Patrimonio', '¿Qué es el patrimonio cultural?', ['Bienes materiales e inmateriales heredados que definen una cultura', 'Solo monumentos', 'Solo dinero', 'Solo libros'], 'Bienes materiales e inmateriales heredados que definen una cultura', 'Incluye arquitectura, tradiciones, lenguas, danzas, gastronomía y más.'),
    mc('s2art-b2-02', 'Popular', 'Los alebrijes son figuras artesanales de:', ['Oaxaca y Ciudad de México', 'Japón', 'Francia', 'Egipto'], 'Oaxaca y Ciudad de México', 'Los alebrijes son criaturas fantásticas talladas o de cartonería, coloridas y detalladas.'),
    tf('s2art-b2-03', 'Patrimonio', 'El Día de Muertos es patrimonio inmaterial de la humanidad por la UNESCO', 'Verdadero', 'En 2003, la UNESCO reconoció esta tradición mexicana como patrimonio cultural inmaterial.'),
    mc('s2art-b2-04', 'Popular', '¿Qué es el papel picado?', ['Artesanía de papel recortado con diseños decorativos', 'Un tipo de comida', 'Un deporte', 'Una canción'], 'Artesanía de papel recortado con diseños decorativos', 'El papel picado decora fiestas y altares de Día de Muertos con figuras caladas en papel.'),
    mc('s2art-b2-05', 'Patrimonio', '¿Cuál es el museo de arte más importante de México?', ['El Museo Nacional de Arte (MUNAL) y Bellas Artes', 'No hay museos', 'Solo museos privados', 'Solo museos en Europa'], 'El Museo Nacional de Arte (MUNAL) y Bellas Artes', 'El Palacio de Bellas Artes alberga murales de Rivera, Siqueiros, Tamayo y Orozco.'),
    tf('s2art-b2-06', 'Popular', 'La cerámica de Talavera de Puebla es reconocida mundialmente', 'Verdadero', 'La Talavera poblana tiene denominación de origen y es patrimonio cultural de México.'),
    mc('s2art-b2-07', 'Cultura', '¿Qué arte indígena mexicano usa hilos de colores sobre cera?', ['El arte huichol (wixárika)', 'La pintura al óleo', 'La acuarela', 'El grabado'], 'El arte huichol (wixárika)', 'Los wixáritari crean obras con chaquira y estambre sobre cera de Campeche.'),
    mc('s2art-b2-08', 'Patrimonio', '¿Qué zona arqueológica mexicana es una de las 7 maravillas del mundo moderno?', ['Chichén Itzá', 'Teotihuacán', 'Palenque', 'Monte Albán'], 'Chichén Itzá', 'La pirámide de Kukulcán en Chichén Itzá fue elegida como maravilla mundial en 2007.'),
    tf('s2art-b2-09', 'Popular', 'El corrido es un género musical narrativo tradicional de México', 'Verdadero', 'El corrido cuenta historias de héroes, batallas y vida cotidiana. Es poesía cantada.'),
    mc('s2art-b2-10', 'Cultura', '¿Por qué es importante preservar el arte popular mexicano?', ['Porque representa la identidad, historia y creatividad de los pueblos', 'No es importante', 'Solo para turistas', 'Solo para museos'], 'Porque representa la identidad, historia y creatividad de los pueblos', 'El arte popular transmite saberes ancestrales y mantiene viva la identidad cultural.'),
]);
sv(G, 'artes', 3, 'Creación artística y creatividad', 'Dic-Ene', ['Proceso creativo', 'Técnicas mixtas'], [
    mc('s2art-b3-01', 'Proceso', '¿Cuáles son las etapas del proceso creativo?', ['Inspiración, planificación, creación y reflexión', 'Solo copiar', 'Solo improvisar', 'Solo dibujar'], 'Inspiración, planificación, creación y reflexión', 'El proceso creativo va desde la idea hasta la obra terminada, con evaluación constante.'),
    mc('s2art-b3-02', 'Técnicas', '¿Qué es la técnica mixta en arte?', ['Combinar diferentes materiales y técnicas en una sola obra', 'Usar solo lápiz', 'Usar solo pintura', 'No usar ningún material'], 'Combinar diferentes materiales y técnicas en una sola obra', 'La técnica mixta permite collage, pintura, dibujo y objetos en una misma pieza.'),
    tf('s2art-b3-03', 'Creatividad', 'La creatividad se puede desarrollar con práctica', 'Verdadero', 'La creatividad no es un don fijo; se entrena y mejora con práctica y exploración.'),
    mc('s2art-b3-04', 'Proceso', '¿Qué es un portafolio artístico?', ['Colección organizada de las mejores obras de un artista', 'Un tipo de pintura', 'Un instrumento musical', 'Un escenario'], 'Colección organizada de las mejores obras de un artista', 'El portafolio muestra la evolución y las habilidades del artista a lo largo del tiempo.'),
    mc('s2art-b3-05', 'Técnicas', 'El collage consiste en:', ['Pegar diferentes materiales sobre una superficie', 'Solo dibujar', 'Solo pintar', 'Solo esculpir'], 'Pegar diferentes materiales sobre una superficie', 'El collage combina recortes, telas, papeles y objetos creando composiciones nuevas.'),
    tf('s2art-b3-06', 'Creatividad', 'Cometer errores en el proceso artístico es parte normal de la creación', 'Verdadero', 'Los errores en arte pueden convertirse en descubrimientos y nuevas posibilidades.'),
    mc('s2art-b3-07', 'Grabado', '¿Qué es el grabado?', ['Técnica donde se talla una imagen en una superficie para imprimirla', 'Tomar fotografías', 'Hacer esculturas', 'Escribir poesía'], 'Técnica donde se talla una imagen en una superficie para imprimirla', 'José Guadalupe Posada fue el gran grabador mexicano, creador de "La Catrina".'),
    mc('s2art-b3-08', 'Proceso', '¿Qué artista mexicano creó "La Catrina"?', ['José Guadalupe Posada', 'Diego Rivera', 'Frida Kahlo', 'Rufino Tamayo'], 'José Guadalupe Posada', 'Posada creó la calavera garbancera, que Rivera bautizó como "La Catrina".'),
    tf('s2art-b3-09', 'Técnicas', 'La escultura es arte tridimensional', 'Verdadero', 'La escultura ocupa espacio en tres dimensiones: alto, ancho y profundidad.'),
    mc('s2art-b3-10', 'Creatividad', '¿Cuál es la mejor fuente de inspiración artística?', ['La observación del mundo, las emociones y la cultura propia', 'Solo copiar a otros', 'Solo usar internet', 'No hay inspiración'], 'La observación del mundo, las emociones y la cultura propia', 'El arte más auténtico surge de la experiencia personal y la sensibilidad hacia el entorno.'),
]);
sv(G, 'artes', 4, 'Música y danza contemporánea', 'Feb-Mar', ['Géneros musicales actuales', 'Danza moderna'], [
    mc('s2art-b4-01', 'Música', '¿Qué es un género musical?', ['Categoría que agrupa música con características similares', 'El nombre de una canción', 'El instrumento principal', 'La duración de la canción'], 'Categoría que agrupa música con características similares', 'Rock, pop, hip-hop, reggaetón, cumbia, son géneros con estilos y ritmos propios.'),
    mc('s2art-b4-02', 'Danza', '¿Qué caracteriza a la danza contemporánea?', ['Libertad de movimiento y expresión personal', 'Solo pasos clásicos de ballet', 'Solo folclor', 'No tiene técnica'], 'Libertad de movimiento y expresión personal', 'La danza contemporánea rompe reglas del ballet clásico para explorar nuevas formas de expresión.'),
    tf('s2art-b4-03', 'Música', 'El hip-hop incluye rap, breakdance, graffiti y DJing', 'Verdadero', 'El hip-hop es una cultura con 4 elementos: MC (rap), DJ, breakdance y graffiti.'),
    mc('s2art-b4-04', 'Música', '¿Qué instrumento es fundamental en la música electrónica?', ['Sintetizador y computadora', 'Solo guitarra', 'Solo violín', 'Solo flauta'], 'Sintetizador y computadora', 'La música electrónica se crea y manipula con tecnología digital.'),
    mc('s2art-b4-05', 'Danza', '¿Quién es considerada la madre de la danza moderna?', ['Isadora Duncan', 'Frida Kahlo', 'Martha Graham', 'Madonna'], 'Isadora Duncan', 'Duncan rompió con el ballet clásico creando movimientos libres inspirados en la naturaleza.'),
    tf('s2art-b4-06', 'Música', 'La música mexicana solo incluye mariachi', 'Falso', 'México tiene cumbia, banda, norteño, son jarocho, hip-hop mexicano, rock en español y más.'),
    mc('s2art-b4-07', 'Música', '¿Qué es un sample en música?', ['Un fragmento de una canción existente reutilizado en una nueva', 'Un instrumento', 'Un género', 'Una nota musical'], 'Un fragmento de una canción existente reutilizado en una nueva', 'El sampling toma fragmentos de grabaciones existentes para crear nueva música.'),
    mc('s2art-b4-08', 'Danza', 'El breakdance fue incluido como deporte olímpico en:', ['París 2024', 'Tokio 2020', 'Atenas 2004', 'Beijing 2008'], 'París 2024', 'El breaking debutó como disciplina olímpica en los Juegos de París 2024.'),
    tf('s2art-b4-09', 'Música', 'Componer música es una forma de expresión artística', 'Verdadero', 'Componer permite expresar emociones, ideas y experiencias de forma sonora.'),
    mc('s2art-b4-10', 'Danza', '¿Por qué la danza es importante para la salud?', ['Ejercita el cuerpo, mejora la coordinación y libera endorfinas', 'Solo es entretenimiento', 'No tiene beneficios', 'Solo es para profesionales'], 'Ejercita el cuerpo, mejora la coordinación y libera endorfinas', 'Bailar combina ejercicio cardiovascular con expresión emocional y socialización.'),
]);
sv(G, 'artes', 5, 'Proyecto artístico integrador', 'Abr-Jun', ['Interdisciplina', 'Proyecto final'], [
    mc('s2art-b5-01', 'Proyecto', '¿Qué es un proyecto artístico integrador?', ['Obra que combina varios lenguajes artísticos', 'Solo un dibujo', 'Solo una canción', 'Solo un baile'], 'Obra que combina varios lenguajes artísticos', 'Un proyecto integrador puede unir música, danza, teatro y artes visuales en una sola presentación.'),
    mc('s2art-b5-02', 'Interdisciplina', '¿Qué es la interdisciplina en el arte?', ['Combinar diferentes disciplinas artísticas en una obra', 'Solo una disciplina', 'No mezclar nada', 'Arte sin reglas'], 'Combinar diferentes disciplinas artísticas en una obra', 'La interdisciplina enriquece la obra al integrar diversas formas de expresión.'),
    tf('s2art-b5-03', 'Proyecto', 'Un proyecto artístico necesita planificación previa', 'Verdadero', 'La planificación incluye: idea, boceto, materiales, ejecución y presentación.'),
    mc('s2art-b5-04', 'Crítica', '¿Qué es la crítica constructiva en arte?', ['Comentario que señala fortalezas y áreas de mejora con respeto', 'Solo insultar', 'Solo elogiar sin fundamento', 'Ignorar la obra'], 'Comentario que señala fortalezas y áreas de mejora con respeto', 'La crítica constructiva ayuda al artista a crecer sin destruir su motivación.'),
    mc('s2art-b5-05', 'Proyecto', '¿Qué elementos debe tener la presentación de un proyecto artístico?', ['Obra, ficha técnica, explicación del proceso y reflexión', 'Solo mostrar la obra', 'Solo hablar', 'Solo el título'], 'Obra, ficha técnica, explicación del proceso y reflexión', 'Presentar el proceso creativo es tan importante como la obra misma.'),
    tf('s2art-b5-06', 'Interdisciplina', 'Un videoclip musical combina artes visuales, música y a veces danza', 'Verdadero', 'Los videoclips son productos artísticos interdisciplinarios muy populares.'),
    mc('s2art-b5-07', 'Reflexión', '¿Por qué es importante reflexionar sobre nuestra obra artística?', ['Para aprender del proceso y mejorar en futuras creaciones', 'No es importante', 'Solo para el maestro', 'Para presumir'], 'Para aprender del proceso y mejorar en futuras creaciones', 'La reflexión cierra el ciclo creativo y genera aprendizaje significativo.'),
    mc('s2art-b5-08', 'Proyecto', '¿Qué es una exposición artística?', ['Presentación organizada de obras para el público', 'Guardar todo en cajas', 'Una clase normal', 'Un examen escrito'], 'Presentación organizada de obras para el público', 'Las exposiciones permiten compartir el trabajo artístico y recibir retroalimentación.'),
    tf('s2art-b5-09', 'Creatividad', 'El proceso creativo es tan valioso como el resultado final', 'Verdadero', 'En el arte, el camino de creación enseña tanto o más que la obra terminada.'),
    mc('s2art-b5-10', 'Arte', '¿Cuál es el propósito principal del arte?', ['Expresar, comunicar y transformar la realidad', 'Solo decorar', 'Solo ganar dinero', 'Solo entretener'], 'Expresar, comunicar y transformar la realidad', 'El arte es un lenguaje poderoso que puede cambiar percepciones y transformar sociedades.'),
]);

// ═══ ED. FÍSICA ═══
console.log('\n🏃 ED. FÍSICA — ' + G);
sv(G, 'educacion_fisica', 1, 'Condición física y entrenamiento', 'Ago-Sep', ['Test de condición', 'Principios del entrenamiento'], [
    mc('s2ef-b1-01', 'Test', '¿Qué mide el test de Cooper?', ['La resistencia aeróbica (distancia en 12 minutos)', 'La fuerza máxima', 'La velocidad de reacción', 'La flexibilidad'], 'La resistencia aeróbica (distancia en 12 minutos)', 'En el test de Cooper se corre durante 12 minutos y se mide la distancia recorrida.'),
    mc('s2ef-b1-02', 'Principios', '¿Qué es el principio de sobrecarga progresiva?', ['Aumentar gradualmente la dificultad del ejercicio', 'Hacer siempre lo mismo', 'Reducir el ejercicio', 'No entrenar'], 'Aumentar gradualmente la dificultad del ejercicio', 'Para mejorar, debemos exigir un poco más al cuerpo de forma gradual y segura.'),
    tf('s2ef-b1-03', 'Entrenamiento', 'El principio de especificidad dice que mejoramos en lo que practicamos', 'Verdadero', 'Si practicas natación, mejorarás en natación. El cuerpo se adapta al tipo de ejercicio.'),
    mc('s2ef-b1-04', 'Test', '¿Qué mide la prueba de flexibilidad sit-and-reach?', ['La flexibilidad de la espalda baja y los isquiotibiales', 'La velocidad máxima', 'La fuerza de brazos', 'La resistencia'], 'La flexibilidad de la espalda baja y los isquiotibiales', 'Se sienta con piernas extendidas y se estira hacia adelante midiendo centímetros.'),
    mc('s2ef-b1-05', 'Principios', '¿Por qué es importante la variedad en el entrenamiento?', ['Para trabajar todos los grupos musculares y evitar el aburrimiento', 'No es importante', 'Para cansarse más rápido', 'Solo para atletas profesionales'], 'Para trabajar todos los grupos musculares y evitar el aburrimiento', 'La variedad previene el sobreentrenamiento de una sola zona y mantiene la motivación.'),
    tf('s2ef-b1-06', 'Entrenamiento', 'Los días de descanso son parte esencial del entrenamiento', 'Verdadero', 'El músculo crece y se repara durante el descanso, no durante el ejercicio.'),
    mc('s2ef-b1-07', 'Frecuencia', 'La zona de frecuencia cardíaca ideal para quemar grasa es:', ['60-70% de la frecuencia cardíaca máxima', '100% siempre', 'Solo en reposo', 'Menos del 40%'], '60-70% de la frecuencia cardíaca máxima', 'En esta zona el cuerpo usa principalmente grasa como combustible.'),
    mc('s2ef-b1-08', 'Test', '¿Para qué sirven los test de condición física?', ['Para conocer nuestro nivel actual y planificar mejoras', 'Para competir contra otros', 'Solo para deportistas', 'No sirven'], 'Para conocer nuestro nivel actual y planificar mejoras', 'Los test establecen un punto de partida para diseñar un plan de mejora personalizado.'),
    tf('s2ef-b1-09', 'Principios', 'El principio de reversibilidad dice que perdemos condición si dejamos de entrenar', 'Verdadero', 'Si dejamos el ejercicio, las adaptaciones del cuerpo se pierden gradualmente.'),
    mc('s2ef-b1-10', 'Entrenamiento', '¿Qué es el entrenamiento HIIT?', ['Intervalos de alta intensidad alternados con descansos cortos', 'Ejercicio suave y continuo', 'Solo estiramientos', 'Solo caminar'], 'Intervalos de alta intensidad alternados con descansos cortos', 'HIIT = High Intensity Interval Training. Muy eficiente en poco tiempo.'),
]);
sv(G, 'educacion_fisica', 2, 'Deportes de adversario', 'Oct-Nov', ['Deportes individuales', 'Estrategia individual'], [
    mc('s2ef-b2-01', 'Adversario', '¿Qué es un deporte de adversario?', ['Deporte donde compites directamente contra un oponente', 'Solo deportes de equipo', 'Juegos de mesa', 'Deportes sin contacto'], 'Deporte donde compites directamente contra un oponente', 'Tenis, judo, esgrima, boxeo y taekwondo son deportes de adversario.'),
    mc('s2ef-b2-02', 'Defensa', '¿Cuál es el origen del taekwondo?', ['Corea del Sur', 'Japón', 'China', 'Brasil'], 'Corea del Sur', 'El taekwondo es un arte marcial coreano olímpico que enfatiza las patadas.'),
    tf('s2ef-b2-03', 'Adversario', 'En los deportes de adversario, respetar al oponente es fundamental', 'Verdadero', 'El respeto al rival es la base de las artes marciales y todos los deportes de combate.'),
    mc('s2ef-b2-04', 'Estrategia', '¿Qué es la estrategia en un deporte individual?', ['Plan de acción para aprovechar fortalezas y explotar debilidades del rival', 'Solo atacar sin pensar', 'Solo defenderse', 'No tener plan'], 'Plan de acción para aprovechar fortalezas y explotar debilidades del rival', 'La estrategia combina inteligencia táctica con habilidad física.'),
    mc('s2ef-b2-05', 'Tenis', '¿Cuántos sets necesita ganar un jugador para ganar un partido de Grand Slam masculino?', ['3 de 5 sets', '1 set', '2 de 3 sets', '4 de 7 sets'], '3 de 5 sets', 'En Grand Slams masculinos se juegan al mejor de 5 sets.'),
    tf('s2ef-b2-06', 'Artes marciales', 'El judo significa "camino de la flexibilidad" o "camino suave"', 'Verdadero', 'Ju = suave/flexible, Do = camino. El judo usa la fuerza del oponente a tu favor.'),
    mc('s2ef-b2-07', 'Defensa', '¿Cuál es la primera regla de la autodefensa personal?', ['Evitar el conflicto y alejarse si es posible', 'Atacar primero', 'Provocar al oponente', 'Nunca retirarse'], 'Evitar el conflicto y alejarse si es posible', 'La mejor defensa es prevenir. Solo se usa la defensa personal como último recurso.'),
    mc('s2ef-b2-08', 'Adversario', '¿Qué deporte de adversario es olímpico y usa espadas?', ['Esgrima', 'Kendo', 'Lucha libre', 'Boxeo'], 'Esgrima', 'La esgrima usa tres tipos de armas: espada, florete y sable.'),
    tf('s2ef-b2-09', 'Respeto', 'En artes marciales, el saludo al oponente simboliza respeto mutuo', 'Verdadero', 'El saludo es tradición en todas las artes marciales y representa honor y respeto.'),
    mc('s2ef-b2-10', 'Estrategia', '¿Qué es la anticipación en deportes de adversario?', ['Prever la acción del rival antes de que ocurra', 'Adivinar sin observar', 'Solo reaccionar', 'No pensar'], 'Prever la acción del rival antes de que ocurra', 'La anticipación se desarrolla observando patrones y movimientos del oponente.'),
]);
sv(G, 'educacion_fisica', 3, 'Salud integral del adolescente', 'Dic-Ene', ['Cambios en la adolescencia', 'Bienestar emocional'], [
    mc('s2ef-b3-01', 'Adolescencia', '¿Qué cambios físicos ocurren durante la pubertad?', ['Crecimiento acelerado, desarrollo muscular y cambios hormonales', 'Ningún cambio', 'Solo cambios mentales', 'Solo cambios sociales'], 'Crecimiento acelerado, desarrollo muscular y cambios hormonales', 'La pubertad trae cambios físicos significativos que afectan el rendimiento deportivo.'),
    mc('s2ef-b3-02', 'Bienestar', '¿Cómo ayuda el ejercicio a la salud mental del adolescente?', ['Reduce estrés, ansiedad y mejora la autoestima', 'No ayuda en nada', 'Solo cansa más', 'Aumenta el estrés'], 'Reduce estrés, ansiedad y mejora la autoestima', 'Las endorfinas liberadas durante el ejercicio mejoran el estado de ánimo y la confianza.'),
    tf('s2ef-b3-03', 'Adolescencia', 'Es normal sentirse diferente y tener cambios de humor en la adolescencia', 'Verdadero', 'Los cambios hormonales causan fluctuaciones emocionales. Es parte normal del desarrollo.'),
    mc('s2ef-b3-04', 'Sueño', '¿Cuántas horas de sueño necesita un adolescente?', ['8 a 10 horas', '4 a 5 horas', 'Solo 3 horas', '12 a 14 horas'], '8 a 10 horas', 'El sueño es fundamental para el crecimiento, la memoria y la recuperación muscular.'),
    mc('s2ef-b3-05', 'Nutrición', 'Durante la adolescencia, ¿por qué es importante el calcio?', ['Para el crecimiento y fortalecimiento de los huesos', 'Solo para los dientes', 'No es importante', 'Solo para adultos'], 'Para el crecimiento y fortalecimiento de los huesos', 'La adolescencia es la etapa de mayor acumulación de masa ósea. El calcio es clave.'),
    tf('s2ef-b3-06', 'Bienestar', 'Hablar sobre nuestras emociones con alguien de confianza es saludable', 'Verdadero', 'Expresar emociones reduce la carga emocional y ayuda a encontrar soluciones.'),
    mc('s2ef-b3-07', 'Imagen', '¿Cuál es una actitud saludable hacia la imagen corporal?', ['Aceptar nuestro cuerpo y cuidarlo con ejercicio y buena alimentación', 'Compararnos constantemente con modelos', 'Solo enfocarnos en el peso', 'Hacer dietas extremas'], 'Aceptar nuestro cuerpo y cuidarlo con ejercicio y buena alimentación', 'La autoaceptación combinada con hábitos saludables es la base de una imagen corporal positiva.'),
    mc('s2ef-b3-08', 'Prevención', '¿Qué sustancias dañan gravemente la salud del adolescente?', ['Alcohol, tabaco y drogas', 'Solo las verduras', 'El agua', 'El ejercicio'], 'Alcohol, tabaco y drogas', 'Estas sustancias dañan órganos en desarrollo y generan adicción.'),
    tf('s2ef-b3-09', 'Ejercicio', 'El ejercicio regular mejora la calidad del sueño', 'Verdadero', 'La actividad física promueve un sueño más profundo y reparador.'),
    mc('s2ef-b3-10', 'Bienestar', '¿Cuáles son los pilares del bienestar integral?', ['Salud física, mental, emocional y social', 'Solo salud física', 'Solo buenas notas', 'Solo tener amigos'], 'Salud física, mental, emocional y social', 'El bienestar integral abarca todas las dimensiones de la vida.'),
]);
sv(G, 'educacion_fisica', 4, 'Deportes alternativos y recreación', 'Feb-Mar', ['Nuevos deportes', 'Actividades recreativas'], [
    mc('s2ef-b4-01', 'Ultimate', '¿Cuál es la regla más especial del Ultimate Frisbee?', ['No hay árbitro: los jugadores se autorregulan (Spirit of the Game)', 'Hay 3 árbitros', 'Se permite el contacto', 'No tiene reglas'], 'No hay árbitro: los jugadores se autorregulan (Spirit of the Game)', 'El Spirit of the Game promueve honestidad, respeto y autoárbitraje.'),
    mc('s2ef-b4-02', 'Recreación', '¿Qué diferencia la actividad recreativa del deporte competitivo?', ['La recreación prioriza la diversión; el deporte, el resultado', 'No hay diferencia', 'La recreación es más difícil', 'El deporte no tiene reglas'], 'La recreación prioriza la diversión; el deporte, el resultado', 'La recreación busca el disfrute personal sin la presión de ganar.'),
    tf('s2ef-b4-03', 'Alternativos', 'El parkour es una disciplina que consiste en desplazarse superando obstáculos', 'Verdadero', 'El parkour desarrolla fuerza, agilidad, coordinación y creatividad del movimiento.'),
    mc('s2ef-b4-04', 'Alternativos', '¿Qué es el slackline?', ['Equilibrio sobre una cinta elástica tensada entre dos puntos', 'Un deporte acuático', 'Un tipo de carrera', 'Un baile'], 'Equilibrio sobre una cinta elástica tensada entre dos puntos', 'El slackline desarrolla equilibrio, concentración y fuerza del core.'),
    mc('s2ef-b4-05', 'Recreación', '¿Por qué son importantes las actividades recreativas?', ['Reducen estrés, fomentan socialización y mantienen activo al cuerpo', 'No son importantes', 'Solo para niños pequeños', 'Solo los fines de semana'], 'Reducen estrés, fomentan socialización y mantienen activo al cuerpo', 'La recreación equilibra la vida académica con el bienestar físico y social.'),
    tf('s2ef-b4-06', 'Alternativos', 'El CrossFit adaptado puede practicarse por adolescentes con supervisión', 'Verdadero', 'Con supervisión y cargas adecuadas, el entrenamiento funcional es beneficioso para adolescentes.'),
    mc('s2ef-b4-07', 'Alternativos', '¿Qué es el flag football?', ['Futbol americano sin contacto, usando banderines', 'Futbol con banderas en la portería', 'Soccer con las manos', 'Voleibol adaptado'], 'Futbol americano sin contacto, usando banderines', 'El flag elimina las tacleadas, haciéndolo seguro e inclusivo.'),
    mc('s2ef-b4-08', 'Recreación', '¿Qué actividad recreativa combina ejercicio con exploración de la naturaleza?', ['Senderismo/hiking', 'Ajedrez', 'Lectura', 'Videojuegos'], 'Senderismo/hiking', 'El senderismo ejercita el cuerpo mientras conectamos con el medio ambiente.'),
    tf('s2ef-b4-09', 'Inclusión', 'Los deportes alternativos son más inclusivos porque se adaptan fácilmente', 'Verdadero', 'Al no tener tradiciones rígidas, se pueden modificar reglas para incluir a todos.'),
    mc('s2ef-b4-10', 'Recreación', '¿Cuál es el mejor beneficio de combinar deporte y diversión?', ['Se mantiene la motivación a largo plazo', 'Solo perder peso', 'Solo competir', 'Solo ganar'], 'Se mantiene la motivación a largo plazo', 'Cuando disfrutamos una actividad, la hacemos consistentemente y se vuelve hábito.'),
]);
sv(G, 'educacion_fisica', 5, 'Proyecto deportivo y vida activa', 'Abr-Jun', ['Plan de vida activa', 'Evaluación personal'], [
    mc('s2ef-b5-01', 'Plan', '¿Qué incluye un plan personal de actividad física?', ['Objetivos, frecuencia, tipo de ejercicio y evaluación', 'Solo correr diario', 'Solo ir al gimnasio', 'No incluye nada'], 'Objetivos, frecuencia, tipo de ejercicio y evaluación', 'Un buen plan es personalizado, medible y tiene seguimiento regular.'),
    mc('s2ef-b5-02', 'Evaluación', '¿Para qué sirve autoevaluar nuestro rendimiento físico?', ['Para identificar avances y ajustar el plan de entrenamiento', 'Para compararnos con los demás', 'Solo por calificación', 'No sirve'], 'Para identificar avances y ajustar el plan de entrenamiento', 'La autoevaluación nos hace conscientes de nuestro progreso y áreas de mejora.'),
    tf('s2ef-b5-03', 'Vida activa', 'Una persona con vida activa tiene menor riesgo de enfermedades crónicas', 'Verdadero', 'La actividad física regular reduce el riesgo de diabetes, hipertensión y enfermedades del corazón.'),
    mc('s2ef-b5-04', 'Plan', '¿Cómo establecemos metas de actividad física realistas?', ['Usando el método SMART: específicas, medibles, alcanzables, relevantes y con tiempo', 'Metas imposibles', 'Sin metas', 'Copiar las metas de otros'], 'Usando el método SMART: específicas, medibles, alcanzables, relevantes y con tiempo', 'Las metas SMART tienen mayor probabilidad de cumplirse.'),
    mc('s2ef-b5-05', 'Hábitos', '¿Cuánto tiempo toma formar un hábito de ejercicio?', ['Aproximadamente 21 a 66 días', 'Solo 1 día', 'Un año', 'Nunca se forma'], 'Aproximadamente 21 a 66 días', 'La investigación sugiere que un nuevo hábito se consolida entre 3 semanas y 2 meses.'),
    tf('s2ef-b5-06', 'Vida activa', 'El ejercicio regular puede mejorar la concentración en los estudios', 'Verdadero', 'El flujo sanguíneo al cerebro durante el ejercicio mejora la memoria y la atención.'),
    mc('s2ef-b5-07', 'Evaluación', '¿Qué es un diario de entrenamiento?', ['Registro escrito de ejercicios, tiempos, sensaciones y progreso', 'Una revista de deportes', 'Un libro de texto', 'Un cuaderno de matemáticas'], 'Registro escrito de ejercicios, tiempos, sensaciones y progreso', 'El diario permite analizar patrones, prevenir sobreentrenamiento y celebrar avances.'),
    mc('s2ef-b5-08', 'Plan', '¿Cuál es la actividad física más accesible del mundo?', ['Caminar', 'Esquí acuático', 'Golf', 'Polo'], 'Caminar', 'Caminar no requiere equipo, dinero ni habilidades especiales. Es universal.'),
    tf('s2ef-b5-09', 'Vida activa', 'La OMS considera la inactividad física como la cuarta causa de muerte mundial', 'Verdadero', 'El sedentarismo causa más muertes que la obesidad sola, según datos de la OMS.'),
    mc('s2ef-b5-10', 'Compromiso', '¿Cuál es tu compromiso contigo mismo/a respecto a la actividad física?', ['Mantenerme activo/a de por vida porque me hace sentir bien', 'Solo hacer ejercicio cuando me obliguen', 'No hacer nada', 'Solo en la escuela'], 'Mantenerme activo/a de por vida porque me hace sentir bien', 'La motivación interna es la que mantiene un estilo de vida activo para siempre.'),
]);

console.log('\n✅ SECUNDARIA 2° — Artes (50) + Ed. Física (50) = 100 ejercicios COMPLETOS');
