const fs = require('fs'), p = require('path');
const BASE = p.join(__dirname, '..', 'src', 'data', 'exercises');
function mc(id, t, q, ops, r, exp) { return { id, tema: t, tipo: 'multiple_choice', nivel: 'v1', pregunta: q, opciones: ops, respuestaCorrecta: r, explicacion: exp }; }
function tf(id, t, q, r, exp) { return { id, tema: t, tipo: 'true_false', nivel: 'v1', pregunta: q, opciones: ['Verdadero', 'Falso'], respuestaCorrecta: r, explicacion: exp }; }
function sv(g, m, b, n, mes, ts, ejs) {
    const d = p.join(BASE, g, m); fs.mkdirSync(d, { recursive: true });
    fs.writeFileSync(p.join(d, 'bloque-' + b + '.json'), JSON.stringify({ grado: g, materia: m, bloque: b, nombre: n, meses: mes, temas: ts, totalEjercicios: ejs.length, ejercicios: { v1: ejs, v2: [], preview: ejs.slice(0, 2) } }, null, 2));
    console.log('  ✅ ' + g + '/' + m + '/bloque-' + b + ' (' + ejs.length + ' ejs)');
}
const G = 'secundaria-3';

// ═══ ARTES ═══
console.log('\n🎨 ARTES — ' + G);
sv(G, 'artes', 1, 'Arte como medio de transformación social', 'Ago-Sep', ['Arte y sociedad', 'Activismo artístico'], [
    mc('s3art-b1-01', 'Social', '¿Cómo puede el arte transformar la sociedad?', ['Creando conciencia, denunciando injusticias e inspirando cambios', 'No puede influir', 'Solo decorando', 'Solo entreteniendo'], 'Creando conciencia, denunciando injusticias e inspirando cambios', 'El arte tiene poder para visibilizar problemas y movilizar a las personas hacia el cambio.'),
    mc('s3art-b1-02', 'Activismo', '¿Qué es el arte activista?', ['Arte que aborda problemas sociales para generar conciencia y acción', 'Arte sin mensaje', 'Solo decoración bonita', 'Arte solo para museos'], 'Arte que aborda problemas sociales para generar conciencia y acción', 'El arte activista usa la creatividad como herramienta de cambio social.'),
    tf('s3art-b1-03', 'Social', 'Los murales comunitarios pueden fortalecer la identidad de un barrio', 'Verdadero', 'Los murales transforman espacios públicos y generan sentido de pertenencia comunitaria.'),
    mc('s3art-b1-04', 'Historia', '¿Qué movimiento artístico denunció los horrores de la guerra?', ['El Guernica de Picasso y el expresionismo', 'El impresionismo', 'El renacimiento', 'El romanticismo'], 'El Guernica de Picasso y el expresionismo', 'El Guernica denuncia el bombardeo de la ciudad española durante la Guerra Civil.'),
    mc('s3art-b1-05', 'Social', 'El street art (arte urbano) puede ser una forma de:', ['Expresión cultural, denuncia social y embellecimiento urbano', 'Solo vandalismo', 'Solo decoración', 'Nada significativo'], 'Expresión cultural, denuncia social y embellecimiento urbano', 'El arte urbano legítimo transforma espacios y comunica mensajes importantes.'),
    tf('s3art-b1-06', 'Activismo', 'La música de protesta ha influido en movimientos sociales en la historia', 'Verdadero', 'Canciones de protesta han acompañado movimientos por derechos civiles, paz y justicia.'),
    mc('s3art-b1-07', 'Social', '¿Cómo usaron los muralistas mexicanos el arte para la sociedad?', ['Educaron al pueblo sobre su historia y derechos en murales públicos', 'Solo decoraron palacios', 'Solo pintaron paisajes', 'No tenían mensaje'], 'Educaron al pueblo sobre su historia y derechos en murales públicos', 'El muralismo fue un proyecto educativo y político para un país con alto analfabetismo.'),
    mc('s3art-b1-08', 'Activismo', '¿Qué es una intervención artística?', ['Acción temporal que modifica un espacio público con arte', 'Un deporte', 'Una clase normal', 'Un examen'], 'Acción temporal que modifica un espacio público con arte', 'Las intervenciones sorprenden al público y provocan reflexión sobre el entorno.'),
    tf('s3art-b1-09', 'Social', 'El teatro puede usarse como herramienta educativa y de sensibilización', 'Verdadero', 'El teatro-foro y el teatro social abordan problemas reales buscando soluciones colectivas.'),
    mc('s3art-b1-10', 'Social', '¿Cuál es la responsabilidad social del artista?', ['Usar su talento para contribuir al diálogo y bienestar social', 'No tiene responsabilidad', 'Solo ganar fama', 'Solo vender obras'], 'Usar su talento para contribuir al diálogo y bienestar social', 'El artista puede ser voz de su comunidad y agente de cambio positivo.'),
]);
sv(G, 'artes', 2, 'Corrientes artísticas del siglo XX', 'Oct-Nov', ['Vanguardias', 'Arte moderno', 'Posmodernismo'], [
    mc('s3art-b2-01', 'Vanguardias', '¿Qué caracteriza a las vanguardias artísticas?', ['Ruptura con la tradición y búsqueda de nuevas formas de expresión', 'Continuar la tradición', 'Copiar el arte clásico', 'No innovar'], 'Ruptura con la tradición y búsqueda de nuevas formas de expresión', 'Las vanguardias del s.XX revolucionaron la pintura, música, literatura y danza.'),
    mc('s3art-b2-02', 'Surrealismo', '¿Qué busca representar el surrealismo?', ['El mundo de los sueños y el inconsciente', 'La realidad fotográfica', 'Solo paisajes', 'Solo retratos'], 'El mundo de los sueños y el inconsciente', 'Salvador Dalí y René Magritte exploraron imágenes oníricas e irracionales.'),
    tf('s3art-b2-03', 'Pop Art', 'El Pop Art usó imágenes de la cultura popular y el consumismo', 'Verdadero', 'Andy Warhol y Roy Lichtenstein elevaron la publicidad y los cómics a categoría artística.'),
    mc('s3art-b2-04', 'Abstracto', 'Wassily Kandinsky es considerado padre del:', ['Arte abstracto', 'Realismo', 'Impresionismo', 'Renacimiento'], 'Arte abstracto', 'Kandinsky fue el primero en crear pinturas completamente no figurativas.'),
    mc('s3art-b2-05', 'Posmoderno', '¿Qué caracteriza al arte posmoderno?', ['Mezcla de estilos, cuestionamiento y uso de medios diversos', 'Un solo estilo puro', 'Solo pintura al óleo', 'Arte sin mensaje'], 'Mezcla de estilos, cuestionamiento y uso de medios diversos', 'El posmodernismo rompe fronteras entre disciplinas y cuestiona qué es arte.'),
    tf('s3art-b2-06', 'Impresionismo', 'El impresionismo capturaba los efectos de la luz y el momento', 'Verdadero', 'Monet, Renoir y Degas pintaban escenas cotidianas con pinceladas sueltas y luminosas.'),
    mc('s3art-b2-07', 'Dadaísmo', '¿Qué proponía el dadaísmo?', ['Cuestionar todo, incluso el concepto mismo de arte', 'Seguir las reglas del arte clásico', 'Solo pintar paisajes', 'Copiar fotográficamente'], 'Cuestionar todo, incluso el concepto mismo de arte', 'Dadá fue anti-arte: protestaba contra la guerra y la sociedad burguesa.'),
    mc('s3art-b2-08', 'México', '¿Qué artista mexicano combinó tradición prehispánica con modernismo?', ['Rufino Tamayo', 'Claude Monet', 'Pablo Picasso', 'Salvador Dalí'], 'Rufino Tamayo', 'Tamayo fusionó la paleta oaxaqueña con las vanguardias europeas.'),
    tf('s3art-b2-09', 'Vanguardias', 'El cubismo muestra un objeto desde múltiples ángulos simultáneamente', 'Verdadero', 'Picasso y Braque descompusieron objetos en formas geométricas vistas desde varios puntos.'),
    mc('s3art-b2-10', 'Contemporáneo', '¿Qué medio usa el arte digital?', ['Computadora, software, IA y medios electrónicos', 'Solo pincel y lienzo', 'Solo mármol', 'Solo instrumentos acústicos'], 'Computadora, software, IA y medios electrónicos', 'El arte digital incluye diseño, animación, arte generativo e inteligencia artificial.'),
]);
sv(G, 'artes', 3, 'Producción artística interdisciplinaria', 'Dic-Ene', ['Multimedia', 'Interdisciplina avanzada'], [
    mc('s3art-b3-01', 'Multimedia', '¿Qué es una obra multimedia?', ['Obra que combina imagen, sonido, texto y/o interactividad', 'Solo una pintura', 'Solo una canción', 'Solo un texto'], 'Obra que combina imagen, sonido, texto y/o interactividad', 'Las obras multimedia integran diferentes medios para una experiencia más completa.'),
    mc('s3art-b3-02', 'Interdisciplina', 'Un videoclip musical es ejemplo de arte:', ['Interdisciplinario: combina música, danza, fotografía y narrativa', 'Solo visual', 'Solo musical', 'Solo teatral'], 'Interdisciplinario: combina música, danza, fotografía y narrativa', 'Los videoclips son productos artísticos complejos que integran múltiples lenguajes.'),
    tf('s3art-b3-03', 'Tecnología', 'La tecnología ha ampliado las posibilidades de creación artística', 'Verdadero', 'Software de edición, realidad virtual, IA generativa y más abren nuevos caminos creativos.'),
    mc('s3art-b3-04', 'Cine', 'El cine se considera el séptimo arte porque:', ['Integra las 6 artes anteriores: arquitectura, escultura, pintura, música, danza y literatura', 'Es el más caro', 'Es el más antiguo', 'Solo entretiene'], 'Integra las 6 artes anteriores: arquitectura, escultura, pintura, música, danza y literatura', 'El cine combina elementos de todas las artes clásicas en un medio audiovisual.'),
    mc('s3art-b3-05', 'Multimedia', '¿Qué es una instalación interactiva?', ['Obra que responde a las acciones del espectador', 'Un cuadro en la pared', 'Una escultura clásica', 'Un libro'], 'Obra que responde a las acciones del espectador', 'Las instalaciones interactivas usan sensores y tecnología para que el público sea parte de la obra.'),
    tf('s3art-b3-06', 'Interdisciplina', 'La ópera combina música, teatro, danza y artes visuales', 'Verdadero', 'La ópera es una de las formas artísticas más completas e interdisciplinarias.'),
    mc('s3art-b3-07', 'Digital', '¿Qué es el arte generativo?', ['Arte creado con algoritmos y código de computadora', 'Pintura a mano', 'Fotografía analógica', 'Escultura en piedra'], 'Arte creado con algoritmos y código de computadora', 'El arte generativo usa programación para que la computadora genere obras únicas.'),
    mc('s3art-b3-08', 'Proyecto', '¿Cómo se documenta un proyecto artístico multimedia?', ['Con bitácora, fotografías, video y reflexión escrita', 'Solo con el título', 'No se documenta', 'Solo con una foto'], 'Con bitácora, fotografías, video y reflexión escrita', 'La documentación completa permite analizar y compartir el proceso creativo.'),
    tf('s3art-b3-09', 'Cine', 'La animación puede transmitir mensajes tan profundos como el cine convencional', 'Verdadero', 'Películas animadas como las de Ghibli o Pixar abordan temas complejos y emocionales.'),
    mc('s3art-b3-10', 'Multimedia', '¿Qué habilidad del siglo XXI desarrolla la creación multimedia?', ['Pensamiento creativo, digital y comunicación efectiva', 'Solo memorización', 'Solo copia', 'Solo cálculo'], 'Pensamiento creativo, digital y comunicación efectiva', 'Crear multimedia requiere combinar creatividad, tecnología y narrativa.'),
]);
sv(G, 'artes', 4, 'Crítica y apreciación artística', 'Feb-Mar', ['Análisis de obras', 'Criterios estéticos'], [
    mc('s3art-b4-01', 'Crítica', '¿Qué es la crítica de arte?', ['Análisis informado que interpreta y valora una obra artística', 'Solo decir si gusta o no', 'Solo insultar al artista', 'Solo describir colores'], 'Análisis informado que interpreta y valora una obra artística', 'La crítica profesional contextualiza, interpreta y evalúa con argumentos fundamentados.'),
    mc('s3art-b4-02', 'Análisis', 'Para analizar una obra de arte debemos considerar:', ['Contexto histórico, técnica, composición, tema y mensaje', 'Solo el precio', 'Solo el tamaño', 'Solo el color'], 'Contexto histórico, técnica, composición, tema y mensaje', 'Un análisis completo examina qué, cómo, cuándo, por qué y para qué de la obra.'),
    tf('s3art-b4-03', 'Apreciación', 'El arte es subjetivo: cada persona puede interpretarlo de diferente manera', 'Verdadero', 'Aunque hay criterios técnicos, la interpretación personal es válida y enriquece el diálogo.'),
    mc('s3art-b4-04', 'Estética', '¿Qué es la estética?', ['Rama de la filosofía que estudia la belleza y el arte', 'Un tipo de cirugía', 'Solo el maquillaje', 'La moda'], 'Rama de la filosofía que estudia la belleza y el arte', 'La estética reflexiona sobre qué es bello, qué es arte y por qué nos conmueve.'),
    mc('s3art-b4-05', 'Análisis', '¿Qué es el contexto de una obra de arte?', ['Las circunstancias históricas, sociales y personales en que fue creada', 'Solo dónde está el museo', 'Solo el precio', 'Solo el tamaño del lienzo'], 'Las circunstancias históricas, sociales y personales en que fue creada', 'El contexto explica por qué el artista creó la obra y qué significaba en su época.'),
    tf('s3art-b4-06', 'Crítica', 'Una buena crítica de arte debe argumentar sus opiniones con fundamentos', 'Verdadero', 'La crítica profesional se basa en conocimiento técnico, histórico y estético, no en gustos.'),
    mc('s3art-b4-07', 'Apreciación', '¿Por qué es importante aprender a apreciar el arte?', ['Desarrolla sensibilidad, pensamiento crítico y comprensión cultural', 'No es importante', 'Solo para artistas', 'Solo para museos'], 'Desarrolla sensibilidad, pensamiento crítico y comprensión cultural', 'La apreciación artística enriquece nuestra percepción del mundo y de las demás culturas.'),
    mc('s3art-b4-08', 'Análisis', '¿Qué significa que una obra tenga "equilibrio compositivo"?', ['Que sus elementos están distribuidos armónicamente en el espacio', 'Que pesa igual en ambos lados', 'Que es simétrica siempre', 'Que tiene muchos colores'], 'Que sus elementos están distribuidos armónicamente en el espacio', 'El equilibrio puede ser simétrico o asimétrico y genera armonía visual.'),
    tf('s3art-b4-09', 'Apreciación', 'Visitar museos y galerías amplía nuestra cultura artística', 'Verdadero', 'La exposición directa al arte desarrolla la sensibilidad y el vocabulario visual.'),
    mc('s3art-b4-10', 'Crítica', '¿Cuál es la diferencia entre opinión y crítica fundamentada?', ['La crítica se basa en argumentos y conocimiento; la opinión en gustos personales', 'Son lo mismo', 'La opinión es más válida', 'La crítica no existe'], 'La crítica se basa en argumentos y conocimiento; la opinión en gustos personales', 'Ambas son válidas pero la crítica aporta un análisis más profundo y educativo.'),
]);
sv(G, 'artes', 5, 'Mi voz artística: proyecto de vida creativa', 'Abr-Jun', ['Identidad artística', 'Portfolio final'], [
    mc('s3art-b5-01', 'Identidad', '¿Qué es la identidad artística?', ['El estilo y voz únicos que cada persona desarrolla al crear arte', 'Copiar a un artista famoso', 'No tener estilo', 'Solo seguir tendencias'], 'El estilo y voz únicos que cada persona desarrolla al crear arte', 'La identidad artística se construye explorando, experimentando y encontrando tu voz.'),
    mc('s3art-b5-02', 'Portfolio', '¿Qué debe incluir un portfolio artístico de fin de curso?', ['Mejores obras, proceso creativo, reflexiones y evolución artística', 'Solo una obra', 'Solo calificaciones', 'Solo fotos'], 'Mejores obras, proceso creativo, reflexiones y evolución artística', 'El portfolio muestra el crecimiento y las habilidades desarrolladas durante el ciclo.'),
    tf('s3art-b5-03', 'Carrera', 'Las carreras artísticas son una opción profesional válida', 'Verdadero', 'Diseño, cine, música, animación, arquitectura y más son profesiones artísticas con demanda.'),
    mc('s3art-b5-04', 'Reflexión', '¿Qué aprendiste en 3 años de Artes en secundaria?', ['Técnicas, historia del arte, expresión personal y apreciación cultural', 'Solo a dibujar', 'Nada', 'Solo nombres de artistas'], 'Técnicas, historia del arte, expresión personal y apreciación cultural', 'Artes desarrolla creatividad, sensibilidad, análisis y comunicación visual.'),
    mc('s3art-b5-05', 'Futuro', '¿Dónde se puede seguir estudiando artes después de la secundaria?', ['En bachilleratos con enfoque artístico, talleres y programas culturales', 'En ningún lugar', 'Solo en el extranjero', 'Solo si tienes mucho dinero'], 'En bachilleratos con enfoque artístico, talleres y programas culturales', 'Existen opciones accesibles para continuar la formación artística.'),
    tf('s3art-b5-06', 'Identidad', 'El arte puede ser una herramienta para comprenderse a uno mismo', 'Verdadero', 'La creación artística es un espejo de nuestras emociones, deseos y experiencias.'),
    mc('s3art-b5-07', 'Creatividad', '¿Cuál es la mejor forma de encontrar tu estilo artístico?', ['Experimentar con diferentes técnicas, estilos y materiales', 'Copiar siempre a los mismos artistas', 'No intentar nada nuevo', 'Solo seguir tutoriales'], 'Experimentar con diferentes técnicas, estilos y materiales', 'La exploración libre es el camino hacia una voz artística auténtica.'),
    mc('s3art-b5-08', 'Sociedad', '¿Cómo puede el arte contribuir a tu comunidad?', ['Embelleciendo espacios, educando, uniendo y creando identidad', 'No puede contribuir', 'Solo si ganas premios', 'Solo si es famoso'], 'Embelleciendo espacios, educando, uniendo y creando identidad', 'El arte comunitario transforma barrios y fortalece lazos sociales.'),
    tf('s3art-b5-09', 'Carrera', 'La creatividad desarrollada en Artes es útil en cualquier profesión', 'Verdadero', 'El pensamiento creativo, la comunicación visual y la innovación son valiosos en todas las áreas.'),
    mc('s3art-b5-10', 'Reflexión', '¿Cuál es el mensaje más importante que te deja Artes?', ['El arte es un derecho y una habilidad que todos podemos desarrollar', 'Solo los talentosos pueden hacer arte', 'El arte no sirve para nada', 'El arte es solo diversión'], 'El arte es un derecho y una habilidad que todos podemos desarrollar', 'Todo ser humano es creativo. El arte es una forma de expresión universal y accesible.'),
]);

// ═══ ED. FÍSICA ═══
console.log('\n🏃 ED. FÍSICA — ' + G);
sv(G, 'educacion_fisica', 1, 'Alto rendimiento y preparación física', 'Ago-Sep', ['Planificación avanzada', 'Periodización'], [
    mc('s3ef-b1-01', 'Periodización', '¿Qué es la periodización del entrenamiento?', ['Organizar el entrenamiento en fases con objetivos específicos', 'Entrenar igual siempre', 'No planificar', 'Solo descansar'], 'Organizar el entrenamiento en fases con objetivos específicos', 'La periodización tiene fases de preparación, competencia y transición.'),
    mc('s3ef-b1-02', 'Preparación', '¿Qué zonas de frecuencia cardíaca existen?', ['Baja, moderada, alta y máxima', 'Solo una zona', 'No hay zonas', 'Solo la máxima'], 'Baja, moderada, alta y máxima', 'Cada zona de FC tiene diferentes beneficios: quema grasa, resistencia, potencia.'),
    tf('s3ef-b1-03', 'Rendimiento', 'El sobreentrenamiento puede causar lesiones y bajo rendimiento', 'Verdadero', 'Entrenar en exceso sin descanso lleva a fatiga crónica, lesiones y rendimiento decreciente.'),
    mc('s3ef-b1-04', 'Preparación', '¿Qué es el VO₂ máx?', ['El volumen máximo de oxígeno que el cuerpo puede usar durante el ejercicio', 'La velocidad máxima de carrera', 'El peso máximo que puedes levantar', 'La flexibilidad máxima'], 'El volumen máximo de oxígeno que el cuerpo puede usar durante el ejercicio', 'El VO₂ máx es el indicador más importante de capacidad aeróbica.'),
    mc('s3ef-b1-05', 'Rendimiento', '¿Por qué es importante el descanso en atletas?', ['El cuerpo repara tejidos y consolida las adaptaciones del entrenamiento', 'No es importante en atletas', 'Solo para principiantes', 'El descanso es perder tiempo'], 'El cuerpo repara tejidos y consolida las adaptaciones del entrenamiento', 'Sin descanso adecuado, el cuerpo no puede adaptarse y mejorar.'),
    tf('s3ef-b1-06', 'Preparación', 'La nutrición es tan importante como el entrenamiento para el rendimiento', 'Verdadero', 'Sin nutrición adecuada, el cuerpo no tiene combustible ni materiales para mejorar.'),
    mc('s3ef-b1-07', 'Planificación', 'Un macrociclo en entrenamiento corresponde a:', ['Una temporada completa (generalmente un año)', 'Una semana', 'Un día', 'Un ejercicio'], 'Una temporada completa (generalmente un año)', 'Macrociclo > mesociclo (mes) > microciclo (semana) > sesión de entrenamiento.'),
    mc('s3ef-b1-08', 'Preparación', '¿Qué es el entrenamiento cruzado (cross-training)?', ['Combinar diferentes actividades deportivas para mejorar el rendimiento general', 'Solo un deporte', 'No entrenar', 'Solo correr'], 'Combinar diferentes actividades deportivas para mejorar el rendimiento general', 'El cross-training previene lesiones y trabaja capacidades complementarias.'),
    tf('s3ef-b1-09', 'Rendimiento', 'La mentalidad y la motivación son factores clave en el rendimiento deportivo', 'Verdadero', 'La psicología deportiva reconoce que la mente es tan importante como el cuerpo en el deporte.'),
    mc('s3ef-b1-10', 'Preparación', '¿Qué es la supercompensación?', ['El cuerpo se adapta por encima del nivel inicial tras descanso adecuado', 'Entrenar sin parar', 'No mejorar nunca', 'Solo perder peso'], 'El cuerpo se adapta por encima del nivel inicial tras descanso adecuado', 'Estímulo + descanso = el cuerpo se recupera más fuerte. Es la base del progreso.'),
]);
sv(G, 'educacion_fisica', 2, 'Gestión y organización deportiva', 'Oct-Nov', ['Eventos deportivos', 'Administración del deporte'], [
    mc('s3ef-b2-01', 'Organización', '¿Qué se necesita para organizar un torneo escolar?', ['Reglamento, calendario, equipos, árbitros y logística', 'Solo un balón', 'Solo una cancha', 'Nada en especial'], 'Reglamento, calendario, equipos, árbitros y logística', 'La organización deportiva requiere planificación en todos los aspectos.'),
    mc('s3ef-b2-02', 'Eventos', '¿Qué formato de torneo permite que todos los equipos se enfrenten entre sí?', ['Todos contra todos (round robin)', 'Eliminación directa', 'Solo un partido', 'Lotería'], 'Todos contra todos (round robin)', 'En round robin cada equipo juega contra todos, el que sume más puntos gana.'),
    tf('s3ef-b2-03', 'Arbitraje', 'Un buen árbitro debe ser imparcial, conocer las reglas y mantener el control', 'Verdadero', 'El árbitro garantiza el juego limpio y la seguridad de todos los participantes.'),
    mc('s3ef-b2-04', 'Liderazgo', 'Un capitán de equipo efectivo debe:', ['Motivar, comunicar, dar ejemplo y mediar conflictos', 'Solo gritar órdenes', 'Jugar solo para él', 'No comunicarse'], 'Motivar, comunicar, dar ejemplo y mediar conflictos', 'El liderazgo deportivo combina habilidades técnicas con inteligencia emocional.'),
    mc('s3ef-b2-05', 'Eventos', '¿Qué es un acta de juego?', ['Documento oficial que registra resultados, incidencias y alineaciones', 'Una carta', 'Un cuento', 'Una receta'], 'Documento oficial que registra resultados, incidencias y alineaciones', 'El acta es el registro oficial de todo lo ocurrido durante un partido.'),
    tf('s3ef-b2-06', 'Organización', 'Organizar eventos deportivos desarrolla habilidades de gestión y liderazgo', 'Verdadero', 'La organización deportiva enseña planificación, delegación, comunicación y resolución de problemas.'),
    mc('s3ef-b2-07', 'Gestión', '¿Cuáles son las fases de un evento deportivo?', ['Planeación, ejecución y evaluación', 'Solo el día del evento', 'Solo la premiación', 'No tiene fases'], 'Planeación, ejecución y evaluación', 'Cada fase es fundamental para un evento exitoso y bien organizado.'),
    mc('s3ef-b2-08', 'Eventos', '¿Cuál es el papel de los voluntarios en un evento deportivo?', ['Apoyan la logística, atención, arbitraje menor y servicio al público', 'No son importantes', 'Solo observan', 'Solo comen'], 'Apoyan la logística, atención, arbitraje menor y servicio al público', 'Los voluntarios son esenciales para que un evento funcione correctamente.'),
    tf('s3ef-b2-09', 'Gestión', 'La evaluación post-evento ayuda a mejorar futuros eventos', 'Verdadero', 'Analizar qué funcionó y qué no permite perfeccionar la organización para el próximo evento.'),
    mc('s3ef-b2-10', 'Liderazgo', '¿Qué aprendemos de la gestión deportiva para la vida?', ['Planificación, trabajo en equipo, comunicación y responsabilidad', 'Nada aplicable', 'Solo a competir', 'Solo a ganar'], 'Planificación, trabajo en equipo, comunicación y responsabilidad', 'Las habilidades organizativas deportivas son directamente transferibles a la vida profesional.'),
]);
sv(G, 'educacion_fisica', 3, 'Primeros auxilios avanzados', 'Dic-Ene', ['RCP y DEA', 'Urgencias deportivas'], [
    mc('s3ef-b3-01', 'RCP', '¿Cuál es la secuencia correcta de RCP?', ['CAB: Compresiones, Abrir vía aérea, dar Respiraciones (si se está entrenado)', 'ABC siempre', 'Solo respiraciones', 'Solo compresiones'], 'CAB: Compresiones, Abrir vía aérea, dar Respiraciones (si se está entrenado)', 'La secuencia actual prioriza compresiones cardíacas inmediatas.'),
    mc('s3ef-b3-02', 'DEA', '¿Qué es un DEA?', ['Desfibrilador Externo Automático: aparato que analiza y puede corregir el ritmo cardíaco', 'Un medicamento', 'Un vendaje especial', 'Un tipo de suero'], 'Desfibrilador Externo Automático: aparato que analiza y puede corregir el ritmo cardíaco', 'Los DEA son fáciles de usar, dan instrucciones por voz y salvan vidas.'),
    tf('s3ef-b3-03', 'Urgencias', 'Ante asfixia por atragantamiento, la maniobra de Heimlich puede salvar vidas', 'Verdadero', 'La maniobra de Heimlich expulsa el objeto que obstruye la vía aérea con compresiones abdominales.'),
    mc('s3ef-b3-04', 'Emergencia', '¿Cuál es la cadena de supervivencia?', ['Reconocer, llamar al 911, RCP, DEA, atención médica avanzada', 'Solo llamar al doctor', 'Solo esperar', 'No hacer nada'], 'Reconocer, llamar al 911, RCP, DEA, atención médica avanzada', 'Cada eslabón es crucial: el tiempo es vida en una emergencia cardíaca.'),
    mc('s3ef-b3-05', 'Lesiones', '¿Cómo inmovilizamos una posible fractura?', ['Con férula o tablilla, sin mover el hueso, y llamando a servicios médicos', 'Moviendo el hueso para acomodarlo', 'Solo con hielo', 'Solo ignorándola'], 'Con férula o tablilla, sin mover el hueso, y llamando a servicios médicos', 'Inmovilizar previene daño adicional. Solo personal médico debe manipular fracturas.'),
    tf('s3ef-b3-06', 'RCP', 'Las compresiones torácicas deben tener una profundidad de al menos 5 cm en adultos', 'Verdadero', 'Compresiones efectivas deben ser fuertes (5-6 cm), rápidas (100-120/min) y continuas.'),
    mc('s3ef-b3-07', 'Urgencias', '¿Qué hacer ante una convulsión?', ['Proteger a la persona de golpes, NO meter nada en la boca, ponerla de lado al terminar', 'Sujetarla fuerte', 'Meter algo en su boca', 'Echarle agua'], 'Proteger a la persona de golpes, NO meter nada en la boca, ponerla de lado al terminar', 'El mito de meter algo en la boca es PELIGROSO. Solo proteger y esperar.'),
    mc('s3ef-b3-08', 'DEA', '¿Cuándo se usa un DEA?', ['Cuando una persona está inconsciente y no respira normalmente', 'Solo en hospitales', 'Solo con entrenamiento especial', 'Nunca por civiles'], 'Cuando una persona está inconsciente y no respira normalmente', 'Los DEA son seguros para uso público y dan instrucciones paso a paso.'),
    tf('s3ef-b3-09', 'Emergencia', 'Saber primeros auxilios puede hacer la diferencia entre la vida y la muerte', 'Verdadero', 'Los primeros minutos son críticos. La atención inmediata salva vidas.'),
    mc('s3ef-b3-10', 'Prevención', '¿Cuál es la mejor prevención de emergencias deportivas?', ['Calentamiento, equipo adecuado, hidratación y reglas de seguridad', 'No prevenir', 'Solo tener botiquín', 'Solo rezar'], 'Calentamiento, equipo adecuado, hidratación y reglas de seguridad', 'La prevención sistemática reduce dramáticamente el riesgo de emergencias.'),
]);
sv(G, 'educacion_fisica', 4, 'Deporte y sociedad', 'Feb-Mar', ['Deporte como derecho', 'Igualdad de género en el deporte'], [
    mc('s3ef-b4-01', 'Derechos', '¿Es la actividad física un derecho?', ['Sí, la ONU reconoce el deporte como derecho humano', 'No, es un privilegio', 'Solo para algunos', 'Solo para profesionales'], 'Sí, la ONU reconoce el deporte como derecho humano', 'La Carta Internacional de la Educación Física y el Deporte de la UNESCO lo afirma.'),
    mc('s3ef-b4-02', 'Igualdad', '¿Cuándo participaron mujeres por primera vez en los JJOO?', ['París 1900', 'Atenas 1896', 'Los Ángeles 1984', 'Tokio 2020'], 'París 1900', '22 mujeres participaron en tenis y golf en los JJOO de París 1900.'),
    tf('s3ef-b4-03', 'Igualdad', 'Las mujeres pueden practicar todos los deportes al mismo nivel que los hombres', 'Verdadero', 'Las mujeres destacan en todos los deportes. Las barreras son sociales, no biológicas.'),
    mc('s3ef-b4-04', 'Sociedad', '¿Cómo contribuye el deporte a la paz?', ['Une personas de diferentes culturas, razas y religiones', 'Genera más guerras', 'No tiene impacto', 'Solo divide'], 'Une personas de diferentes culturas, razas y religiones', 'Los JJOO fueron creados con el ideal de paz a través del deporte.'),
    mc('s3ef-b4-05', 'Igualdad', '¿Qué son los Juegos Paralímpicos?', ['Competencia olímpica para atletas con discapacidades', 'Juegos para niños', 'Juegos de mesa', 'Solo exhibición'], 'Competencia olímpica para atletas con discapacidades', 'Los Paralímpicos demuestran que el talento deportivo no conoce limitaciones.'),
    tf('s3ef-b4-06', 'Sociedad', 'El deporte puede ser herramienta de prevención de violencia juvenil', 'Verdadero', 'Programas deportivos comunitarios reducen la delincuencia juvenil significativamente.'),
    mc('s3ef-b4-07', 'Ética', '¿Qué es la ética deportiva?', ['Conjunto de valores morales que guían la conducta en el deporte', 'Solo las reglas del juego', 'No existe', 'Solo para profesionales'], 'Conjunto de valores morales que guían la conducta en el deporte', 'La ética deportiva incluye fair play, respeto, honestidad y solidaridad.'),
    mc('s3ef-b4-08', 'Sociedad', '¿Cómo puede el deporte combatir la discriminación?', ['Promoviendo equipos diversos, reglas justas e igualdad de oportunidades', 'Separando a las personas', 'Excluyendo a algunos', 'Ignorando el problema'], 'Promoviendo equipos diversos, reglas justas e igualdad de oportunidades', 'El deporte demuestra que el talento no depende del origen, género o condición social.'),
    tf('s3ef-b4-09', 'Igualdad', 'En los JJOO de Tokio 2020 participaron casi igual número de hombres y mujeres', 'Verdadero', 'Tokio 2020 fue el evento más equitativo en género en la historia olímpica.'),
    mc('s3ef-b4-10', 'Derechos', '¿Cuál es tu responsabilidad como joven deportista?', ['Promover respeto, inclusión y juego limpio en todas las actividades', 'Solo ganar', 'Solo ser famoso', 'No tengo responsabilidad'], 'Promover respeto, inclusión y juego limpio en todas las actividades', 'Cada deportista es embajador de los valores del deporte.'),
]);
sv(G, 'educacion_fisica', 5, 'Proyecto de vida saludable', 'Abr-Jun', ['Plan de vida', 'Transición al bachillerato'], [
    mc('s3ef-b5-01', 'Plan', '¿Qué incluye un proyecto de vida saludable?', ['Ejercicio regular, alimentación balanceada, salud mental y metas personales', 'Solo dieta', 'Solo gimnasio', 'Solo estudiar'], 'Ejercicio regular, alimentación balanceada, salud mental y metas personales', 'Un proyecto de vida saludable integra bienestar físico, mental, emocional y social.'),
    mc('s3ef-b5-02', 'Transición', '¿Cómo puedes mantener una vida activa en el bachillerato?', ['Practicando deportes extraescolares, caminando más y reduciendo sedentarismo', 'Dejando todo el ejercicio', 'Solo estudiando', 'Olvidando la Ed. Física'], 'Practicando deportes extraescolares, caminando más y reduciendo sedentarismo', 'La actividad física es más importante que nunca durante la adolescencia tardía.'),
    tf('s3ef-b5-03', 'Hábitos', 'Los hábitos de ejercicio creados en la secundaria pueden durar toda la vida', 'Verdadero', 'La adolescencia es la etapa clave para consolidar hábitos de vida activa permanentes.'),
    mc('s3ef-b5-04', 'Bienestar', '¿Cuáles son las dimensiones del bienestar integral?', ['Física, mental, emocional, social y espiritual', 'Solo física', 'Solo emocional', 'Solo social'], 'Física, mental, emocional, social y espiritual', 'El bienestar verdadero abarca todas las dimensiones de la persona.'),
    mc('s3ef-b5-05', 'Plan', '¿Cómo se establece un hábito de ejercicio permanente?', ['Empezando con metas pequeñas, siendo consistente y disfrutando el proceso', 'Con metas imposibles', 'De un día para otro', 'Solo con fuerza de voluntad'], 'Empezando con metas pequeñas, siendo consistente y disfrutando el proceso', 'La consistencia supera a la intensidad. Pequeños pasos diarios generan grandes cambios.'),
    tf('s3ef-b5-06', 'Salud', 'El ejercicio regular reduce el riesgo de depresión en adolescentes', 'Verdadero', 'La actividad física libera serotonina y endorfinas, neurotransmisores del bienestar.'),
    mc('s3ef-b5-07', 'Reflexión', '¿Qué te enseñó la Ed. Física en 3 años de secundaria?', ['Capacidades físicas, deportes, nutrición, primeros auxilios, valores y salud integral', 'Solo a correr', 'Solo a jugar futbol', 'Nada'], 'Capacidades físicas, deportes, nutrición, primeros auxilios, valores y salud integral', 'La Ed. Física desarrolla tu cuerpo, tu mente y tus valores para toda la vida.'),
    mc('s3ef-b5-08', 'Plan', '¿Cuál es la mejor motivación para hacer ejercicio?', ['El disfrute personal y sentirse bien', 'Solo la calificación', 'Solo la apariencia', 'Solo la presión social'], 'El disfrute personal y sentirse bien', 'La motivación intrínseca (gozo propio) es la más duradera y efectiva.'),
    tf('s3ef-b5-09', 'Vida', 'Nunca es tarde para empezar una vida activa y saludable', 'Verdadero', 'A cualquier edad se pueden obtener beneficios del ejercicio regular.'),
    mc('s3ef-b5-10', 'Compromiso', 'Tu compromiso de egreso de secundaria es:', ['Ser una persona activa, saludable y promotora del deporte para toda la vida', 'Dejar el ejercicio', 'Olvidar la Ed. Física', 'No importa'], 'Ser una persona activa, saludable y promotora del deporte para toda la vida', '¡Lleva los valores del deporte a tu bachillerato y a toda tu vida! 🚀'),
]);

// ═══ ORIENTACIÓN VOCACIONAL ═══
console.log('\n🧭 ORIENTACIÓN VOCACIONAL — ' + G);
sv(G, 'orientacion', 1, 'Autoconocimiento', 'Ago-Sep', ['Identidad personal', 'Fortalezas y áreas de oportunidad'], [
    mc('s3ov-b1-01', 'Identidad', '¿Qué es el autoconocimiento?', ['Comprender nuestras fortalezas, debilidades, intereses y valores', 'Solo saber nuestro nombre', 'Solo conocer nuestra edad', 'No es posible conocerse'], 'Comprender nuestras fortalezas, debilidades, intereses y valores', 'El autoconocimiento es la base para tomar buenas decisiones sobre nuestro futuro.'),
    mc('s3ov-b1-02', 'Fortalezas', '¿Qué es una fortaleza personal?', ['Habilidad o cualidad en la que destacamos naturalmente', 'Solo ser fuerte físicamente', 'Ser perfecto en todo', 'No cometer errores nunca'], 'Habilidad o cualidad en la que destacamos naturalmente', 'Las fortalezas pueden ser académicas, sociales, artísticas, deportivas o personales.'),
    tf('s3ov-b1-03', 'Identidad', 'Conocer nuestras debilidades nos ayuda a mejorar', 'Verdadero', 'Identificar áreas de oportunidad es el primer paso para desarrollarnos y crecer.'),
    mc('s3ov-b1-04', 'Intereses', '¿Cómo identificamos nuestros intereses?', ['Observando qué actividades disfrutamos más y nos motivan', 'Solo por lo que nos dicen los demás', 'Al azar', 'Solo por la calificación'], 'Observando qué actividades disfrutamos más y nos motivan', 'Los intereses genuinos surgen de aquello que hacemos con gusto y sin presión.'),
    mc('s3ov-b1-05', 'Valores', '¿Qué son los valores personales?', ['Principios que guían nuestras decisiones y comportamiento', 'Solo reglas impuestas', 'Solo costumbres', 'No existen'], 'Principios que guían nuestras decisiones y comportamiento', 'Los valores como honestidad, respeto y responsabilidad definen quiénes somos.'),
    tf('s3ov-b1-06', 'Identidad', 'Todos tenemos habilidades diferentes y eso está bien', 'Verdadero', 'La diversidad de habilidades es lo que hace valioso a cada individuo.'),
    mc('s3ov-b1-07', 'Fortalezas', '¿Cuál es la diferencia entre aptitud y actitud?', ['Aptitud es capacidad, actitud es disposición ante algo', 'Son lo mismo', 'Solo aptitud importa', 'Solo actitud importa'], 'Aptitud es capacidad, actitud es disposición ante algo', 'Ambas son importantes. La aptitud se puede desarrollar y la actitud se puede elegir.'),
    mc('s3ov-b1-08', 'Autoconocimiento', '¿Qué herramienta nos ayuda a conocernos mejor?', ['Tests vocacionales, reflexión personal y retroalimentación de otros', 'Solo un examen', 'Solo la suerte', 'Nada nos ayuda'], 'Tests vocacionales, reflexión personal y retroalimentación de otros', 'Combinar autorreflexión con opiniones de personas de confianza da una visión completa.'),
    tf('s3ov-b1-09', 'Identidad', 'Nuestra identidad se construye a lo largo de la vida, no es fija', 'Verdadero', 'Somos personas en constante desarrollo. Nuestros intereses pueden cambiar y evolucionar.'),
    mc('s3ov-b1-10', 'Valores', '¿Por qué es importante conocer nuestros valores antes de elegir carrera?', ['Para elegir una profesión que sea coherente con lo que nos importa', 'No es importante', 'Solo importa el dinero', 'Solo importa la fama'], 'Para elegir una profesión que sea coherente con lo que nos importa', 'Trabajar en algo alineado a nuestros valores genera satisfacción y sentido de vida.'),
]);
sv(G, 'orientacion', 2, 'Exploración de opciones educativas', 'Oct-Nov', ['Bachillerato', 'Tipos de preparatoria'], [
    mc('s3ov-b2-01', 'Bachillerato', '¿Cuántos años dura el bachillerato en México?', ['3 años (o 2 años en algunos sistemas como CONALEP)', '1 año', '5 años', '10 años'], '3 años (o 2 años en algunos sistemas como CONALEP)', 'La educación media superior generalmente dura 3 años después de la secundaria.'),
    mc('s3ov-b2-02', 'Tipos', '¿Cuál es la diferencia entre preparatoria general y técnica?', ['La general prepara para universidad; la técnica también da una carrera técnica', 'No hay diferencia', 'La técnica es inferior', 'La general no sirve'], 'La general prepara para universidad; la técnica también da una carrera técnica', 'El bachillerato técnico da certificado de preparatoria + título de técnico profesional.'),
    tf('s3ov-b2-03', 'Opciones', 'El CONALEP, CBTIS, CBTa y preparatoria general son opciones de bachillerato', 'Verdadero', 'Existen múltiples modalidades para elegir según intereses y aspiraciones.'),
    mc('s3ov-b2-04', 'Bachillerato', '¿Qué es el COMIPEMS?', ['Concurso de asignación a bachilleratos en la zona metropolitana', 'Un examen de primaria', 'Una carrera universitaria', 'Un tipo de escuela'], 'Concurso de asignación a bachilleratos en la zona metropolitana', 'En la CDMX y zona metropolitana, el COMIPEMS asigna lugares en bachilleratos.'),
    mc('s3ov-b2-05', 'Elección', '¿Qué factores debes considerar para elegir tu bachillerato?', ['Ubicación, plan de estudios, prestigio, costos y tu perfil vocacional', 'Solo cercanía', 'Solo lo que eligen mis amigos', 'Solo el nombre'], 'Ubicación, plan de estudios, prestigio, costos y tu perfil vocacional', 'Una decisión informada considera múltiples factores prácticos y personales.'),
    tf('s3ov-b2-06', 'Opciones', 'El bachillerato en línea o a distancia es una opción válida', 'Verdadero', 'Existen opciones de bachillerato a distancia reconocidas por la SEP.'),
    mc('s3ov-b2-07', 'Tipos', '¿Qué ofrece un bachillerato con especialidad artística?', ['Formación artística especializada además del plan académico', 'Solo arte sin materias regulares', 'Solo matemáticas', 'Nada diferente'], 'Formación artística especializada además del plan académico', 'Escuelas como el CeDArT ofrecen formación artística profesional desde el bachillerato.'),
    mc('s3ov-b2-08', 'Elección', '¿Cuándo debes empezar a investigar opciones de bachillerato?', ['Desde principios de 3° de secundaria', 'En el último mes', 'Después de terminar secundaria', 'No necesitas investigar'], 'Desde principios de 3° de secundaria', 'Investigar temprano te da más tiempo para prepararte y tomar una decisión informada.'),
    tf('s3ov-b2-09', 'Bachillerato', 'El bachillerato es obligatorio en México', 'Verdadero', 'Desde 2012, la educación media superior es obligatoria en México.'),
    mc('s3ov-b2-10', 'Opciones', '¿Qué significa bachillerato bivalente?', ['Obtienes certificado de preparatoria Y título de técnico profesional', 'Solo un certificado', 'Solo prácticas', 'Dos escuelas al mismo tiempo'], 'Obtienes certificado de preparatoria Y título de técnico profesional', 'CBTIS, CBTa y CONALEP ofrecen este doble beneficio educativo.'),
]);
sv(G, 'orientacion', 3, 'Campos profesionales', 'Dic-Ene', ['Áreas del conocimiento', 'Carreras emergentes'], [
    mc('s3ov-b3-01', 'Áreas', '¿Cuáles son las grandes áreas del conocimiento profesional?', ['Ciencias exactas, sociales, humanidades, biológicas, ingenierías y artes', 'Solo medicina', 'Solo derecho', 'Solo ingeniería'], 'Ciencias exactas, sociales, humanidades, biológicas, ingenierías y artes', 'Existe una enorme variedad de áreas profesionales para todos los perfiles.'),
    mc('s3ov-b3-02', 'Emergentes', '¿Qué carreras serán más demandadas en el futuro?', ['Tecnología, IA, energías renovables, biotecnología y ciberseguridad', 'Solo abogado', 'Solo médico', 'Solo contador'], 'Tecnología, IA, energías renovables, biotecnología y ciberseguridad', 'Las carreras del futuro están vinculadas a la transformación digital y sostenibilidad.'),
    tf('s3ov-b3-03', 'Campos', 'Las carreras técnicas pueden ser tan bien remuneradas como las universitarias', 'Verdadero', 'Técnicos especializados en áreas de alta demanda tienen excelentes oportunidades laborales.'),
    mc('s3ov-b3-04', 'Profesiones', '¿Qué profesional diseña edificios y espacios habitables?', ['Arquitecto', 'Médico', 'Abogado', 'Contador'], 'Arquitecto', 'Los arquitectos combinan arte, ciencia y tecnología para diseñar espacios funcionales.'),
    mc('s3ov-b3-05', 'Emergentes', '¿Qué es la inteligencia artificial como campo profesional?', ['Desarrollo de sistemas que aprenden y toman decisiones como humanos', 'Solo robots', 'Ciencia ficción', 'No existe como carrera'], 'Desarrollo de sistemas que aprenden y toman decisiones como humanos', 'La IA es una de las áreas con mayor crecimiento y demanda laboral en el mundo.'),
    tf('s3ov-b3-06', 'Campos', 'El emprendimiento es una opción válida además de trabajar para una empresa', 'Verdadero', 'Crear tu propio negocio es una forma de aplicar tus habilidades y generar empleo.'),
    mc('s3ov-b3-07', 'Profesiones', '¿En qué campo trabaja un psicólogo?', ['Salud mental, educación, organizaciones y desarrollo humano', 'Solo hospitales', 'Solo en el deporte', 'Solo con niños'], 'Salud mental, educación, organizaciones y desarrollo humano', 'La psicología tiene múltiples campos de aplicación profesional.'),
    mc('s3ov-b3-08', 'Emergentes', '¿Qué es la economía naranja?', ['Industrias creativas y culturales que generan valor económico', 'Un tipo de fruta', 'Una empresa', 'No existe'], 'Industrias creativas y culturales que generan valor económico', 'Diseño, cine, videojuegos, moda y gastronomía son parte de la economía creativa.'),
    tf('s3ov-b3-09', 'Campos', 'México tiene universidades públicas gratuitas de alta calidad como la UNAM y el IPN', 'Verdadero', 'La UNAM, IPN, UAM y universidades estatales ofrecen educación gratuita de calidad.'),
    mc('s3ov-b3-10', 'Profesiones', '¿Qué habilidades son transversales a TODAS las profesiones?', ['Comunicación, pensamiento crítico, trabajo en equipo y adaptabilidad', 'Solo memorizar', 'Solo calcular', 'Solo escribir'], 'Comunicación, pensamiento crítico, trabajo en equipo y adaptabilidad', 'Estas habilidades del siglo XXI son valoradas en cualquier campo profesional.'),
]);
sv(G, 'orientacion', 4, 'Toma de decisiones', 'Feb-Mar', ['Proceso de decisión', 'Proyecto de vida'], [
    mc('s3ov-b4-01', 'Decisiones', '¿Cuáles son los pasos para tomar una buena decisión?', ['Identificar opciones, evaluar pros/contras, decidir y actuar', 'Decidir al azar', 'Copiar lo que hacen los demás', 'No pensar'], 'Identificar opciones, evaluar pros/contras, decidir y actuar', 'Un proceso estructurado de decisión reduce la incertidumbre y mejora los resultados.'),
    mc('s3ov-b4-02', 'Proyecto', '¿Qué es un proyecto de vida?', ['Plan personalizado con metas a corto, mediano y largo plazo', 'Solo elegir carrera', 'Solo ganar dinero', 'Solo terminar la escuela'], 'Plan personalizado con metas a corto, mediano y largo plazo', 'El proyecto de vida integra metas personales, académicas, profesionales y sociales.'),
    tf('s3ov-b4-03', 'Decisiones', 'Es normal sentir incertidumbre al tomar decisiones sobre el futuro', 'Verdadero', 'La incertidumbre es natural. Lo importante es informarse y reflexionar antes de decidir.'),
    mc('s3ov-b4-04', 'Proyecto', '¿Qué son metas SMART?', ['Específicas, Medibles, Alcanzables, Relevantes y con Tiempo definido', 'Solo metas grandes', 'Metas imposibles', 'Metas sin plazo'], 'Específicas, Medibles, Alcanzables, Relevantes y con Tiempo definido', 'Las metas SMART son más fáciles de cumplir porque tienen claridad y estructura.'),
    mc('s3ov-b4-05', 'Decisiones', '¿A quién podemos recurrir para orientación vocacional?', ['Orientador escolar, padres, profesores y profesionistas en el campo', 'Solo a internet', 'A nadie', 'Solo al azar'], 'Orientador escolar, padres, profesores y profesionistas en el campo', 'Múltiples fuentes de orientación nos ayudan a tomar decisiones más informadas.'),
    tf('s3ov-b4-06', 'Proyecto', 'Nuestro proyecto de vida puede cambiar y adaptarse con el tiempo', 'Verdadero', 'Un proyecto de vida es flexible. Las circunstancias y nuestros intereses pueden evolucionar.'),
    mc('s3ov-b4-07', 'Decisiones', '¿Qué es un test vocacional?', ['Herramienta que evalúa intereses y aptitudes para sugerir campos afines', 'Un examen de matemáticas', 'Una prueba de sangre', 'Solo un juego'], 'Herramienta que evalúa intereses y aptitudes para sugerir campos afines', 'Los tests vocacionales son orientativos y ayudan a explorar opciones, no determinan.'),
    mc('s3ov-b4-08', 'Proyecto', '¿Cuál es más importante: vocación o estabilidad económica?', ['Lo ideal es encontrar un equilibrio entre ambos', 'Solo el dinero', 'Solo la pasión', 'No importa ninguno'], 'Lo ideal es encontrar un equilibrio entre ambos', 'La satisfacción profesional combina lo que disfrutas con lo que te permite vivir bien.'),
    tf('s3ov-b4-09', 'Decisiones', 'Elegir una carrera a los 15 años no es definitivo; se puede cambiar después', 'Verdadero', 'Muchos profesionistas exitosos cambiaron de carrera o la complementaron con otros estudios.'),
    mc('s3ov-b4-10', 'Proyecto', '¿Cuál es el primer paso de tu proyecto de vida?', ['Conocerte a ti mismo: tus valores, intereses, fortalezas y sueños', 'Ganar mucho dinero', 'Ser famoso', 'No hacer nada'], 'Conocerte a ti mismo: tus valores, intereses, fortalezas y sueños', 'El autoconocimiento es la brújula que guía todas las decisiones de vida.'),
]);
sv(G, 'orientacion', 5, 'Mi futuro empieza hoy', 'Abr-Jun', ['Preparación para el cambio', 'Habilidades para la vida'], [
    mc('s3ov-b5-01', 'Habilidades', '¿Qué son las habilidades socioemocionales?', ['Capacidades para manejar emociones, relaciones y toma de decisiones', 'Solo ser simpático', 'Solo obedecer', 'Solo memorizar'], 'Capacidades para manejar emociones, relaciones y toma de decisiones', 'La inteligencia emocional es clave para el éxito personal y profesional.'),
    mc('s3ov-b5-02', 'Cambio', '¿Cómo te puedes preparar para la transición a bachillerato?', ['Investigando opciones, preparándote académicamente y siendo adaptable', 'Sin hacer nada', 'Solo esperando', 'Teniendo miedo'], 'Investigando opciones, preparándote académicamente y siendo adaptable', 'La preparación reduce la ansiedad y aumenta la confianza ante el cambio.'),
    tf('s3ov-b5-03', 'Habilidades', 'La resiliencia es la capacidad de recuperarse ante las dificultades', 'Verdadero', 'Las personas resilientes enfrentan problemas, aprenden de ellos y salen fortalecidas.'),
    mc('s3ov-b5-04', 'Futuro', '¿Cuál es la habilidad más importante del siglo XXI?', ['Aprender a aprender (capacidad de adaptación y aprendizaje continuo)', 'Memorizar todo', 'Solo usar tecnología', 'Solo hablar inglés'], 'Aprender a aprender (capacidad de adaptación y aprendizaje continuo)', 'En un mundo cambiante, la capacidad de aprender cosas nuevas es la habilidad más valiosa.'),
    mc('s3ov-b5-05', 'Cambio', '¿Por qué es importante desarrollar autonomía?', ['Para tomar nuestras propias decisiones responsablemente', 'Para hacer lo que queramos sin consecuencias', 'Para no pedir ayuda nunca', 'Para aislarnos'], 'Para tomar nuestras propias decisiones responsablemente', 'La autonomía con responsabilidad es signo de madurez y crecimiento personal.'),
    tf('s3ov-b5-06', 'Habilidades', 'El trabajo en equipo es una habilidad fundamental para cualquier profesión', 'Verdadero', 'Prácticamente todas las profesiones requieren colaborar con otros de manera efectiva.'),
    mc('s3ov-b5-07', 'Futuro', '¿Qué actitud te llevará más lejos en la vida?', ['Curiosidad, perseverancia y apertura al aprendizaje', 'Conformismo', 'Indiferencia', 'Solo quejarse'], 'Curiosidad, perseverancia y apertura al aprendizaje', 'Estas tres actitudes son el motor del crecimiento personal y profesional.'),
    mc('s3ov-b5-08', 'Reflexión', '¿Qué aprendiste en Orientación Vocacional?', ['A conocerme, explorar opciones, tomar decisiones y planificar mi futuro', 'Nada', 'Solo a estudiar', 'Solo el nombre de carreras'], 'A conocerme, explorar opciones, tomar decisiones y planificar mi futuro', 'La orientación vocacional te da herramientas para construir tu propio camino.'),
    tf('s3ov-b5-09', 'Futuro', 'Tu futuro lo construyes con las decisiones y acciones que tomas HOY', 'Verdadero', 'Cada decisión diaria, grande o pequeña, contribuye a construir tu futuro.'),
    mc('s3ov-b5-10', 'Compromiso', 'Tu compromiso al egresar de secundaria es:', ['Seguir aprendiendo, ser responsable y construir el futuro que deseas', 'No hacer nada', 'Solo descansar', 'Olvidar todo'], 'Seguir aprendiendo, ser responsable y construir el futuro que deseas', '🎓 ¡Felicidades! Tu camino apenas comienza. ¡Tú puedes lograr lo que te propongas! 🚀'),
]);

console.log('\n✅ SECUNDARIA 3° — Artes (50) + Ed. Física (50) + Orientación (50) = 150 ejercicios COMPLETOS');
console.log('🎉🎉🎉 ¡¡¡TODA LA EDUCACIÓN BÁSICA COMPLETADA AL 100%!!!');
